aptos-labs/aptos-indexer-processors

- python/Dockerfile
- python/README.md
- python/config.yaml
- python/config.yaml.example
- python/poetry.lock
- python/processors/README.md
- python/processors/example_event_processor/event_parser.py
- python/processors/example_event_processor/models/create_table.py
- python/processors/example_event_processor/models/create_tables.py
- python/processors/example_event_processor/models/models.py
- python/processors/example_event_processor/processor.py
- python/utils/config.py
Reorganize the repo based on this [proposed file structure](https://docs.google.com/document/d/1hj_D7p5lqXnS7qJwnQc7yyfBnbJLA9TzO5TK6xH05PY/edit?usp=sharing)
1. poetry run python -m processors.example_event_processor.models.create_table -c config.yaml 
2. poetry run python -m processors.example_event_processor.models.processor -c config.yaml 
3. docker compose up --build --force-recreate
> Reorganize Python files

- python/utils/general_utils.py
- python/utils/token_utils.py
Tested in this [PR](https://github.com/aptos-labs/aptos-indexer-processors/pull/9)
> Add utils files

- python/processors/README.md
- python/processors/aptos_ambassador_token/processor.py
Added a minimal example of indexer processor for tracking the changes in the Aptos ambassador tokens' levels
> Added aptos_ambassador_token example

- python/README.md
- python/processors/example_event_processor/processor.py
* tested locally with fresh docker compose build, processor runs without problem.
> update the processor table creation.

- python/processors/nft_orderbooks/models/nft_marketplace_activities_model.py
- python/processors/nft_orderbooks/models/nft_marketplace_bid_models.py
- python/processors/nft_orderbooks/models/nft_marketplace_listings_models.py
- python/utils/models/general_models.py
- python/utils/transactions_processor.py
> Add schema for nft_marketplace

- python/processors/nft_orderbooks/models/nft_marketplace_activities_model.py
- python/processors/nft_orderbooks/models/nft_marketplace_bid_models.py
- python/processors/nft_orderbooks/models/nft_marketplace_listings_models.py
- python/utils/models/Base.py
- python/utils/models/schema_names.py
poetry run python -m processors.nft_orderbooks.nft_marketplace_processor -c config.yaml
> Move schema name to constant

- python/config.yaml.example
- python/poetry.lock
- python/pyproject.toml
- python/utils/config.py
- python/utils/metrics.py
- python/utils/transactions_processor.py
Locally tested, looks good.
Keep alive check:
> create monitoring and health check port.

- rust/processor/src/worker.rs
* This fixes the client cannot receive 4mb size response with new tonic lib.
* locally tested, looks good
> [rust processor] Unlock the 4MB response limit to 20 MB

- python/processors/aptos_ambassador_token/processor.py
- python/utils/config.py
- python/utils/transactions_processor.py
`poetry run python -m processors.nft_marketplace_v2.processor -c config.yaml`
> Remove chain_id from config.yaml

- python/processors/nft_marketplace_v2/marketplace_v2_parser.py
- python/processors/nft_marketplace_v2/processor.py
- python/utils/config.py
- python/utils/worker.py
`poetry run python -m processors.nft_marketplace_v2.processor -c config.yaml` 
with 
```
custom_config:
marketplace_contract_address: "0x6de37368e31dff4580b211295198159ee6f98b42ffa93c5683bb955ca1be67e0"
```
> Add custom config.yaml variables

- rust/processor/src/models/token_models/v2_token_ownerships.rs
Explained here https://github.com/aptos-labs/aptos-core/pull/9195
> [Indexer] fix self transfer bug

- python/README.md
- python/processors/nft_marketplace_v2/constants.py
- python/processors/nft_marketplace_v2/processor.py
- python/utils/worker.py
* Adds documentation on starting the marketplace
* Fixes typing issue
* removes unused constants
> [python] Marketplace v2 fixes

- rust/processor/migrations/2023-07-28-053854_entry_function/down.sql
- rust/processor/migrations/2023-07-28-053854_entry_function/up.sql
- rust/processor/src/processors/coin_processor.rs
- rust/processor/src/processors/default_processor.rs
- rust/processor/src/processors/token_processor.rs
- rust/processor/src/schema.rs
- rust/processor/src/utils/util.rs
Turns out that the current max is 142 so this is too short.
> [Indexer] Fix over truncation of entry function string

- rust/Cargo.lock
- rust/Cargo.toml
- rust/processor/Cargo.toml
- rust/processor/src/models/token_models/nft_points.rs
- rust/processor/src/utils/util.rs
Turns out that the payload needs escaping. It crashes now. The fix works.
> [Rust] Fix nft points bug from escaped payload

- rust/Cargo.lock
- rust/Cargo.toml
- rust/processor/Cargo.toml
- rust/processor/src/main.rs
- rust/processor/src/processors/coin_processor.rs
- rust/processor/src/processors/default_processor.rs
- rust/processor/src/processors/fungible_asset_processor.rs
- rust/processor/src/processors/mod.rs
- rust/processor/src/processors/nft_metadata_processor.rs
- rust/processor/src/processors/processor_trait.rs
- rust/processor/src/processors/stake_processor.rs
- rust/processor/src/processors/token_processor.rs
- rust/processor/src/processors/token_v2_processor.rs
- rust/processor/src/worker.rs
Config used:
```yaml
health_check_port: 8080
server_config:
processor_name: nft_metadata_processor
postgres_connection_string: postgresql://localhost:5432/postgres
indexer_grpc_data_service_address: 35.223.137.149:50051 # testnet
auth_token: TOKEN
starting_version: 476443000
indexer_grpc_http2_ping_interval_in_secs: 30
indexer_grpc_http2_ping_timeout_in_secs: 5
pubsub_topic_name: TOPIC_NAME
google_application_credentials: CREDENTIALS_PATH
```
Starting PubSub topic state:
Running the processor:
PubSub topic state after running the processor:
Everything working as intended, postgres not needed for this processor. 
Fixes EI-287, EI-281
> [NFT Metadata Crawler] NFT Metadata Crawler Processor

- python/processors/coin_flip/README.md
- python/processors/coin_flip/models.py
- python/processors/coin_flip/move/Move.toml
- python/processors/coin_flip/move/sources/coin_flip.move
- python/processors/coin_flip/move/sources/package_manager.move
- python/processors/coin_flip/processor.py
- python/utils/models/schema_names.py
- python/utils/processor_name.py
- python/utils/worker.py
Adding a very basic custom indexer processor tutorial that works off of a simple Move contract that emits CoinFlipEvents for dfiferent accounts.
The tutorial goes the basics of how to setup your environment and processor configuration with a basic explanation of what emitted event data looks like and how to process it.
> [Tutorial] Add a basic custom indexer processor tutorial

- rust/processor/src/processors/nft_metadata_processor.rs
Add missing metadata attributes to token parsing
> [NFT Metadata Crawler] Fix missing metadata

- rust/processor/migrations/2023-08-23-192343_fix_ans_view/down.sql
- rust/processor/migrations/2023-08-23-192343_fix_ans_view/up.sql
Add extra fields for ANS view and filter out deleted names.
> Add extra fields to ans view

- rust/processor/src/processors/nft_metadata_processor.rs
Changed publishing of messages to publish by bulk and added an ordering key of the last transaction timestamp to the messages
> [NFT Metadata Crawler] Bulk publish PubSub messages

- rust/Cargo.lock
- rust/Cargo.toml
- rust/processor/src/worker.rs
Tested locally with `cargo run --release -- -c config.yaml` and it works
> [Rust] Update processors to use API gateway

- python/config.yaml.example
- python/processors/aptos_ambassador_token/processor.py
- python/utils/processor_name.py
- python/utils/worker.py
Also update the ambassador token processor to the new way. For deployment, need to change the config.yaml's. 
`poetry run python -m processors.main -c config.yaml`
> [Python] Update processors to use API gateway

- rust/processor/src/processors/nft_metadata_processor.rs
Chunks the transactions processed so the PubSub 1000 transaction per bulk commit limit isn't exceeded
> [NFT Metadata Crawler] Chunk transaction publish

- rust/processor/src/models/token_v2_models/v2_token_ownerships.rs
If a transaction has a transfer and a burn down the line, we could be logging the burn under the wrong address (the previous owner). 
Query to run
```
select min(transaction_version) from events where type = '0x4::collection::BurnEvent'
```
Mainnet: 151521169
Testnet: 513906597
burn shows up properly
> [Rust] fix issue where we're getting the wrong owner for a burned nft

- rust/Cargo.lock
- rust/Cargo.toml
- rust/post-processor/Cargo.toml
- rust/post-processor/config.yaml
- rust/post-processor/src/lib.rs
- rust/post-processor/src/main.rs
- rust/post-processor/src/metrics.rs
- rust/post-processor/src/processor_status_checker.rs
Adds 2 post processing metrics to the indexer processors: 
- Hasura latest version latency to fullnode latest version 
- Hasura last updated time latency to current time
Plan to deploy this as a cloud run function
> Add processor status checker

- rust/processor/src/config.rs
- rust/processor/src/lib.rs
- rust/processor/src/main.rs
This lets you import it from other places, main should be thin.
> Move Rust processor config into lib

- .github/workflows/check-protos.yaml
- README.md
- typescript/aptos-indexer-protos/CHANGELOG.md
- typescript/aptos-indexer-protos/package.json
- typescript/aptos-indexer-protos/src/aptos/bigquery_schema/v1/transaction.ts
- typescript/aptos-indexer-protos/src/aptos/indexer/v1/raw_data.ts
- typescript/aptos-indexer-protos/src/aptos/internal/fullnode/v1/fullnode_data.ts
- typescript/aptos-indexer-protos/src/aptos/transaction/v1/transaction.ts
- typescript/aptos-indexer-protos/src/aptos/util/timestamp/timestamp.ts
- typescript/examples/event_processor/package.json
- typescript/examples/event_processor/pnpm-lock.yaml
- typescript/sdk/CHANGELOG.md
- typescript/sdk/package.json
- typescript/sdk/pnpm-lock.yaml
There is new version of protoc-gen-ts. In this PR I upgrade us to it and then pin the dep so the CI doesn't break due to another release of the tool in the future.
```
cd typescript/examples/event_processor
pnpm start process --config ~/config.yaml
```
> Regenerate TS proto code

- python/config.yaml.example
- python/processors/nft_marketplace_v2/processor.py
- python/scripts/create_tables.py
- python/utils/config.py
- python/utils/worker.py
Standardize config yaml between Python and Rust processors
Run python processors with different config setups
> [Python] Standardize config yaml 

- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_utils.rs
Related to https://github.com/aptos-labs/aptos-core/pull/10598 @bowenyang007 '
testnet: 553151941
mainnet: 199271122
> fix get_symbol v2 FA

- rust/processor/src/models/user_transactions_models/signatures.rs
* This change adds parsing support for new signature types.
> [Preview] add the signature parsing.

- python/utils/config.py
- python/utils/worker.py
> migrate all logging to use the new util.

- python/Dockerfile
- python/processors/aptos_ambassador_token/processor.py
- python/processors/coin_flip/processor.py
- python/processors/example_event_processor/processor.py
- python/processors/main.py
- python/processors/nft_marketplace_v2/processor.py
- python/processors/nft_orderbooks/nft_marketplace_processor.py
- python/utils/config.py
- python/utils/transactions_processor.py
- python/utils/worker.py
Overall looks good, which aligns with rust logs.
> align python logging with rust ones.

- rust/processor/src/utils/counters.rs
- rust/processor/src/utils/util.rs
- rust/processor/src/worker.rs
* Add timestamp logging and metrics
> Improve logging

- rust/processor/src/worker.rs
1. Increase max reconnection retries
2. Increase time to wait for transactions from GRPC before panic
3. Add a wait in between reconnections
> Increase reconnection times

- rust/Cargo.lock
- rust/Cargo.toml
Unpin serde because serde-reflection bug that prevented upgrading serde is fixed.
> unpin serde

- hasura-api/metadata-json/README.md
- hasura-api/metadata-json/unified.json
Updating based on the latest metadata generated from the script in https://github.com/aptos-labs/internal-ops/pull/2319.
> Update Hasura metadata, add script for cleaning metadata

- rust/processor/migrations/2024-01-12-092310_roulette/down.sql
- rust/processor/migrations/2024-01-12-092310_roulette/up.sql
- rust/processor/src/models/aptos_tournament_models/aptos_tournament_utils.rs
- rust/processor/src/models/aptos_tournament_models/mod.rs
- rust/processor/src/models/aptos_tournament_models/roulette.rs
- rust/processor/src/processors/aptos_tournament_processor.rs
- rust/processor/src/schema.rs
Pretty straight forward roulette game
> add roulette game

- rust/processor/migrations/2023-11-10-004930_create_aptos_tournament_tables/down.sql
- rust/processor/migrations/2023-11-10-004930_create_aptos_tournament_tables/up.sql
- rust/processor/migrations/2024-01-12-092310_roulette/down.sql
- rust/processor/migrations/2024-01-12-092310_roulette/up.sql
- rust/processor/src/models/ans_models/ans_utils.rs
- rust/processor/src/models/aptos_tournament_models/aptos_tournament_utils.rs
- rust/processor/src/models/aptos_tournament_models/mod.rs
- rust/processor/src/models/aptos_tournament_models/rock_paper_scissors_game.rs
- rust/processor/src/models/aptos_tournament_models/rock_paper_scissors_player.rs
- rust/processor/src/models/aptos_tournament_models/roulette.rs
- rust/processor/src/models/aptos_tournament_models/trivia_answer.rs
- rust/processor/src/models/aptos_tournament_models/trivia_question.rs
- rust/processor/src/processors/aptos_tournament_processor.rs
- rust/processor/src/schema.rs
Manually indexing games because it'll probably be faster than finding a common interface to index...
> [Aptos Tournament] Manual game indexing

- rust/processor/src/models/aptos_tournament_models/aptos_tournament_utils.rs
- rust/processor/src/models/aptos_tournament_models/tournament_players.rs
- rust/processor/src/models/aptos_tournament_models/tournament_rooms.rs
- rust/processor/src/models/aptos_tournament_models/tournaments.rs
- rust/processor/src/processors/aptos_tournament_processor.rs
- rust/processor/src/schema.rs
Add events to move code to make it so we have to perform less lookups indexer side
> [Aptos Tournament] Add events remove lookups

- rust/processor/src/models/user_transactions_models/signatures.rs
- rust/processor/src/utils/counters.rs
Run user_transaction_processor
> Remove panic for unknown signature types

- rust/processor/src/models/aptos_tournament_models/aptos_tournament_utils.rs
- rust/processor/src/models/aptos_tournament_models/tournament_players.rs
- rust/processor/src/models/aptos_tournament_models/tournament_rooms.rs
- rust/processor/src/models/aptos_tournament_models/tournaments.rs
- rust/processor/src/processors/aptos_tournament_processor.rs
> [Tournament] Add events remove lookups

- rust/indexer-metrics/src/main.rs
* Use the server time to reflect the indexer latency.
LInter
> update the latency calc to use local time now  instead of server time.

- rust/Cargo.lock
- rust/Cargo.toml
* Bump tokio version to a recent version
* Bump rust version.
> [processor][rust] upgrade rust and tokio.

- rust/Cargo.lock
- rust/Cargo.toml
Same change as https://github.com/aptos-labs/aptos-core/pull/11901, but for processors
> Remove prost recursion limit

- rust/Cargo.lock
- rust/processor/src/grpc_stream.rs
- rust/processor/src/lib.rs
- rust/processor/src/worker.rs
Tested in devnet to ensure compatibility
> Refactor GRPC stream for processor into own file

- rust/processor/src/models/account_transaction_models/account_transactions.rs
- rust/processor/src/models/coin_models/coin_activities.rs
- rust/processor/src/models/coin_models/coin_balances.rs
- rust/processor/src/models/coin_models/coin_infos.rs
- rust/processor/src/models/coin_models/coin_supply.rs
- rust/processor/src/models/default_models/transactions.rs
- rust/processor/src/models/events_models/events.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_activities.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_balances.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_metadata.rs
- rust/processor/src/models/stake_models/delegator_activities.rs
- rust/processor/src/models/stake_models/delegator_balances.rs
- rust/processor/src/models/stake_models/delegator_pools.rs
- rust/processor/src/models/stake_models/proposal_votes.rs
- rust/processor/src/models/stake_models/staking_pool_voter.rs
- rust/processor/src/models/token_models/collection_datas.rs
- rust/processor/src/models/token_models/nft_points.rs
- rust/processor/src/models/token_models/token_activities.rs
- rust/processor/src/models/token_models/token_claims.rs
- rust/processor/src/models/token_models/token_datas.rs
- rust/processor/src/models/token_models/token_ownerships.rs
- rust/processor/src/models/token_models/tokens.rs
- rust/processor/src/models/token_v2_models/v2_collections.rs
- rust/processor/src/models/token_v2_models/v2_token_activities.rs
- rust/processor/src/models/token_v2_models/v2_token_datas.rs
- rust/processor/src/models/token_v2_models/v2_token_metadata.rs
- rust/processor/src/models/token_v2_models/v2_token_ownerships.rs
Sort the dervives alphabetically, like they were before (we should have a linter for this)
> Sort Derives

- rust/Cargo.lock
- rust/Cargo.toml
- rust/processor/Cargo.toml
- rust/processor/src/config.rs
- rust/processor/src/utils/database.rs
- rust/processor/src/worker.rs
Sometimes we need to connect via SSL- diesel_async does not support doing this unfortunately, and this is their preferred way of us handling it
> Add SSL support for PG

- rust/processor/src/models/ans_models/ans_utils.rs
- rust/processor/src/models/coin_models/coin_utils.rs
- rust/processor/src/models/default_models/move_modules.rs
- rust/processor/src/models/default_models/move_resources.rs
- rust/processor/src/models/default_models/move_tables.rs
- rust/processor/src/models/default_models/write_set_changes.rs
- rust/processor/src/models/events_models/events.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_activities.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_balances.rs
- rust/processor/src/models/ledger_info.rs
- rust/processor/src/models/object_models/v2_objects.rs
- rust/processor/src/models/processor_status.rs
- rust/processor/src/models/stake_models/current_delegated_voter.rs
- rust/processor/src/models/stake_models/delegator_balances.rs
- rust/processor/src/models/stake_models/stake_utils.rs
- rust/processor/src/models/token_models/collection_datas.rs
- rust/processor/src/models/token_models/token_utils.rs
- rust/processor/src/models/token_v2_models/v2_collections.rs
- rust/processor/src/models/token_v2_models/v2_token_ownerships.rs
- rust/processor/src/processors/ans_processor.rs
- rust/processor/src/processors/coin_processor.rs
- rust/processor/src/processors/fungible_asset_processor.rs
- rust/processor/src/processors/mod.rs
- rust/processor/src/processors/stake_processor.rs
- rust/processor/src/processors/token_processor.rs
- rust/processor/src/processors/token_v2_processor.rs
- rust/processor/src/utils/counters.rs
- rust/processor/src/utils/database.rs
Ran linter across all files- will make other PRs smaller
> run linter on all files

- rust/processor/src/models/token_v2_models/v2_token_activities.rs
- rust/processor/src/models/token_v2_models/v2_token_utils.rs
- rust/processor/src/processors/token_v2_processor.rs
Handle token burn when the mint happened in the same transaction 
Tested locally on this transaction: https://explorer.aptoslabs.com/txn/445585423/events?network=mainnet
> Fix token burns

- rust/processor/src/config.rs
- rust/processor/src/gap_detector.rs
- rust/processor/src/lib.rs
- rust/processor/src/processors/account_transactions_processor.rs
- rust/processor/src/processors/ans_processor.rs
- rust/processor/src/processors/coin_processor.rs
- rust/processor/src/processors/default_processor.rs
- rust/processor/src/processors/events_processor.rs
- rust/processor/src/processors/fungible_asset_processor.rs
- rust/processor/src/processors/mod.rs
- rust/processor/src/processors/monitoring_processor.rs
- rust/processor/src/processors/nft_metadata_processor.rs
- rust/processor/src/processors/objects_processor.rs
- rust/processor/src/processors/stake_processor.rs
- rust/processor/src/processors/token_processor.rs
- rust/processor/src/processors/token_v2_processor.rs
- rust/processor/src/processors/user_transaction_processor.rs
- rust/processor/src/utils/database.rs
- rust/processor/src/worker.rs
1. Create a gap detector in a separate tokio task
2. Enables parallel parsing and DB inserts while ensuring data completeness
Run locally
> Gap detector

- rust/processor/migrations/2024-02-13-231650_add_tournament_debug_tables/down.sql
- rust/processor/migrations/2024-02-13-231650_add_tournament_debug_tables/up.sql
- rust/processor/src/models/aptos_tournament_models/tournament_players.rs
- rust/processor/src/models/aptos_tournament_models/tournaments.rs
- rust/processor/src/processors/aptos_tournament_processor.rs
- rust/processor/src/schema.rs
> [Tournament] Add debug tables

- rust/Cargo.lock
- rust/post-processor/Cargo.toml
- rust/post-processor/src/processor_status_checker.rs
- rust/processor/src/models/account_transaction_models/account_transactions.rs
- rust/processor/src/models/coin_models/coin_activities.rs
- rust/processor/src/models/default_models/transactions.rs
- rust/processor/src/models/stake_models/delegator_activities.rs
- rust/processor/src/models/stake_models/delegator_pools.rs
- rust/processor/src/models/stake_models/proposal_votes.rs
- rust/processor/src/models/token_models/nft_points.rs
- rust/processor/src/models/token_models/token_activities.rs
- rust/processor/src/models/token_models/tokens.rs
- rust/processor/src/processors/ans_processor.rs
- rust/processor/src/processors/events_processor.rs
- rust/processor/src/processors/fungible_asset_processor.rs
- rust/processor/src/processors/token_v2_processor.rs
- rust/processor/src/processors/user_transaction_processor.rs
- rust/processor/src/utils/counters.rs
* devnet build at  4318127b6848cbdf901834706258a42f7c3da414
* Adds metrics to record if there is incompatibility.  
* Deployed to devnet and looks good.
* Also tested locally, looks good(tested from version `472207`)
> Do not unwrap with new type. 

- rust/processor/src/models/account_transaction_models/account_transactions.rs
- rust/processor/src/models/coin_models/coin_activities.rs
- rust/processor/src/models/default_models/transactions.rs
> fix the unkown type handling.

- rust/processor/src/models/default_models/transactions.rs
TransactionInfo is guaranteed to exist for all transactions. Include it in the processing or transaction table insertions will fail because of the unique constraint on `hash` column. 
Error log: https://gist.githubusercontent.com/rtso/57ce50919175b266a68c41547a3c3a6b/raw/e80ef949051e6894abec049a3f724e760f9d6fd0/gistfile1.txt
Run default processor locally on devnet with txn 551987797 and see that processor doesn't crash
> Fix transaction parsing

- rust/processor/src/models/stake_models/current_delegated_voter.rs
- rust/processor/src/models/stake_models/delegator_balances.rs
- rust/processor/src/models/token_models/collection_datas.rs
- rust/processor/src/models/token_v2_models/v2_token_ownerships.rs
> Remove duplicate import

- rust/processor/src/processors/nft_metadata_processor.rs
Some null bytes appearing in relevant token/collection data: https://mainnet.aptoslabs.com/v1/transactions/by_version/469623165
Log of before and after cleaning
> [NFT Metadata Crawler] Remove null bytes

- test_move_script/Move.toml
- test_move_script/README.md
- test_move_script/sources/run_script.move
Sometimes we need to create edge cases in move. Until we automate here's a super easy way to do this.
> [testing] skeleton for creating move scripts for testing

- rust/processor/migrations/2024-03-07-224504_fungible_asset_metadata_is_token_v2/down.sql
- rust/processor/migrations/2024-03-07-224504_fungible_asset_metadata_is_token_v2/up.sql
- rust/processor/src/models/fungible_asset_models/v2_fungible_metadata.rs
- rust/processor/src/models/object_models/v2_objects.rs
- rust/processor/src/models/token_v2_models/v2_token_datas.rs
- rust/processor/src/models/token_v2_models/v2_token_ownerships.rs
- rust/processor/src/models/token_v2_models/v2_token_utils.rs
- rust/processor/src/processors/objects_processor.rs
- rust/processor/src/processors/token_v2_processor.rs
- rust/processor/src/schema.rs
* Created branch on 31a3f928f589e68bb9635225fadb1193660cc306 (commit before parallelism)
* Cherry pick 93ea78f3a072f7fe713891de99b86eaa37da16d5 and 3bd0c0494a9de2e4d4c884196a82a01176824067
TBD
> Cherry-pick 1.10 changes

- rust/processor/src/models/fungible_asset_models/v2_fungible_metadata.rs
- rust/processor/src/processors/fungible_asset_processor.rs
See https://github.com/aptos-labs/aptos-indexer-processors/pull/314
> [hotfix] Fix fungible asset logic (cherry pick into main)

- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_activities.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_balances.rs
context here: https://github.com/aptos-labs/aptos-indexer-processors/pull/330
> [cherrypick][hotfix] fix panic where coin type is too long

- hasura-api/metadata-json/unified.json
* Changing token ownership -> token ownerships b/c the former is buggy. 
* Expose signatures
* Expose non_transferrable_by_owner field for token ownerships
> [indexer] update hasura metadata for tokens and signature

- hasura-api/metadata-json/unified.json
Join `account_transactions` and `user_transactions` table to get txn detail
[GQL](https://cloud.hasura.io/public/graphiql?endpoint=https%3A%2F%2Fknmpjhsurbz8-testnet.hasura.app%2Fv1%2Fgraphql&query=query+MyQuery+%7B%0A++account_transactions%28%0A++++where%3A+%7Buser_transaction%3A+%7Bversion%3A+%7B_is_null%3A+false%7D%7D%7D%0A++++limit%3A+10%0A++%29+%7B%0A++++user_transaction+%7B%0A++++++block_height%0A++++++entry_function_id_str%0A++++++epoch%0A++++++expiration_timestamp_secs%0A++++++gas_unit_price%0A++++++max_gas_amount%0A++++++parent_signature_type%0A++++++sender%0A++++++sequence_number%0A++++++timestamp%0A++++++version%0A++++%7D%0A++++transaction_version%0A++++account_address%0A++%7D%0A%7D%0A)
> Join tables to get txn detail

- rust/processor/src/config.rs
- rust/processor/src/worker.rs
* Add timeout for transaction fetch receiver.
* Tested in devnet and looks good
> add grpc response item timeout.

- .github/workflows/copy-processor-images-to-dockerhub-release.yaml
- .github/workflows/copy-processor-images-to-dockerhub.yaml
- scripts/release-processor-images.mjs
* only build & release the rust image
* make the GAR repo more clear by using a gh var
> [build] fix vars and rust only build release

- rust/processor/src/grpc_stream.rs
- rust/processor/src/models/stake_models/current_delegated_voter.rs
https://aptos-org.slack.com/archives/C04PRP1K1FZ/p1716469712528289
> Fix lints given new nightly

- hasura-api/metadata-json/unified.json
Update hasura metadata for opensource
> update opensource hasura metadata

- rust/processor/src/db/common/models/default_models/transactions.rs
https://aptos-org.slack.com/archives/C07A7CWF788
tested locally.
> handle payload filtered txns for default processor

- rust/processor/src/db/postgres/migrations/2024-06-26-220144_add_token_standard/down.sql
- rust/processor/src/db/postgres/migrations/2024-06-26-220144_add_token_standard/up.sql
Followup from https://github.com/aptos-labs/aptos-indexer-processors/pull/430
> add if not exists

- rust/processor/src/db/common/models/fungible_asset_models/v2_fungible_asset_activities.rs
- rust/processor/src/db/common/models/fungible_asset_models/v2_fungible_asset_utils.rs
fix fa events tracking in indexer
> [fix] fix fa unrecognized v2 events

- rust/processor/src/db/common/models/fungible_asset_models/v2_fungible_asset_activities.rs
- rust/processor/src/db/common/models/fungible_asset_models/v2_fungible_asset_utils.rs
Reverts aptos-labs/aptos-indexer-processors#445
> Revert "[fix] fix fa unrecognized v2 events"

- rust/processor/src/db/common/models/default_models/parquet_transactions.rs
fix to handle filtered payload, where the behavior changed now due to the newly introduced. filtering feature.
> handle filtered payload txn for parquet

- rust/processor/src/db/postgres/migrations/2024-07-08-182507_truncate_deprecated_tables/up.sql
commenting out queries cause diesel migration to fail. 
deployed on testnet
> fix diesel migration

- rust/processor/Cargo.toml
> [indexer] fix the windows build.

- rust/processor/src/bq_analytics/mod.rs
- rust/processor/src/db/common/models/transaction_metadata_model/mod.rs
- rust/processor/src/db/common/models/transaction_metadata_model/parquet_write_set_size_info.rs
- rust/processor/src/processors/mod.rs
- rust/processor/src/processors/parquet_processors/mod.rs
- rust/processor/src/processors/parquet_processors/parquet_default_processor.rs
- rust/processor/src/processors/parquet_processors/parquet_transaction_metadata_processor.rs
- rust/processor/src/utils/counters.rs
- rust/processor/src/worker.rs
Add write_set_size_info table to parquet
> add parquet txn metadata processor that handles write set size info

- .github/workflows/integration-tests.yaml
we were hitting rate limit on docker hub, so we replace this with runs-on. 
also remove the env variable that we don't need.
> use runs-on

- .github/workflows/copy-processor-images-to-dockerhub.yaml
During the process of verifying whether integ tests runs without any issues during the release, identified an issue with dependency. 
This is to fix. 
tested and verified that tests passed.
https://github.com/aptos-labs/aptos-indexer-processors/actions/runs/10532553862/job/29186930307
> fix release workflow

- rust/processor/src/db/common/models/account_transaction_models/account_transactions.rs
- rust/processor/src/processors/account_transactions_processor.rs
- rust/processor/src/worker.rs
Tested locally using devnet data. See ~10x improvement for the processing part.
> Simplify account_transaction_processor and use rayon to speed it up.

- scripts/get_changes_since_commit.sh
Script copied from API Gateway
> Script to get list of links to changes since previous commit

- rust/Cargo.lock
- rust/Cargo.toml
* Update the sdk dependency to include the latest change for license information.
> Update the dependencies.

- rust/processor/src/processors/default_processor.rs
* Remove the spamming log from default processor.
> Remove spamming logs from default proecssor.

- rust/integration-tests/src/models/default_models.rs
- rust/processor/src/db/common/models/token_v2_models/v2_token_ownerships.rs
- rust/processor/src/db/postgres/schema.rs
- rust/processor/src/processors/token_v2_processor.rs
- rust/sdk-processor/src/config/indexer_processor_config.rs
- rust/sdk-processor/src/config/processor_config.rs
- rust/sdk-processor/src/processors/mod.rs
- rust/sdk-processor/src/processors/token_v2_processor.rs
- rust/sdk-processor/src/steps/mod.rs
- rust/sdk-processor/src/steps/token_v2_processor/mod.rs
- rust/sdk-processor/src/steps/token_v2_processor/token_v2_extractor.rs
- rust/sdk-processor/src/steps/token_v2_processor/token_v2_storer.rs
Migrates token v2 processor to SDK and adds documentation for parsing.
> Migrate token v2 processor to SDK

- .github/workflows/build-images.yaml
- .github/workflows/integration-tests.yaml
pls be faster
taken from https://github.com/actions/cache/blob/main/examples.md#rust---cargo
successfully speeds up the `Build Docker Image` action from ~18mins to ~4mins
> Add Cargo Cache

- rust/sdk-processor/src/config/indexer_processor_config.rs
- rust/sdk-processor/src/config/processor_config.rs
- rust/sdk-processor/src/lib.rs
- rust/sdk-processor/src/parquet_processors/mod.rs
- rust/sdk-processor/src/parquet_processors/parquet_default_processor.rs
https://www.notion.so/aptoslabs/Configuration-File-Support-12d8b846eb728098a227da3b820f3a20?pvs=4
> [parquet-sdk-migration] Config: add a parquet default config to start with

- rust/processor/src/db/common/models/user_transactions_models/parquet_user_transactions.rs
> Number returned is gas in units not octa

- rust/processor/src/db/postgres/models/object_models/v2_object_utils.rs
See discussion in [slack thread](https://aptos-org.slack.com/archives/C083C28ASTC)
> Add dummy_field to Untransferable Object

- rust/processor/src/db/parquet/models/account_transaction_models/parquet_account_transactions.rs
> fix account txn table name for parquet

- .github/workflows/create-release-tag.yaml
- .github/workflows/integration-tests.yaml
- .github/workflows/update-sdk-dependency.yaml
^
Tested with local repo and looks good.
> [3/3] Create github workflow to handle the SDK upgrade in processor repo

- rust/processor/src/db/postgres/migrations/2025-01-07-000504_add_function_columns_to_user_transactions/up.sql
Make index creation concurrently so that it does not block processing
> Make index creation concurrently

- hasura-api/metadata-json/unified.json
Update hasura metadata for open source
> Update hasura metadata

- .github/workflows/update-sdk-dependency.yaml
* Allows the workflow to access the repo secrets.
* Fix the configuration for git.
> Fix the release workflow.

- .github/workflows/update-sdk-dependency.yaml
This is to fix the issue below:
> Fix the permission issue.

- rust/Cargo.lock
- rust/Cargo.toml
- rust/integration-tests/src/sanity_test/sanity_tests.rs
- rust/integration-tests/src/sdk_tests/account_transaction_processor_tests.rs
- rust/integration-tests/src/sdk_tests/ans_processor_tests.rs
- rust/integration-tests/src/sdk_tests/default_processor_tests.rs
- rust/integration-tests/src/sdk_tests/events_processor_tests.rs
- rust/integration-tests/src/sdk_tests/fungible_asset_processor_tests.rs
- rust/integration-tests/src/sdk_tests/objects_processor_tests.rs
- rust/integration-tests/src/sdk_tests/stake_processor_tests.rs
- rust/integration-tests/src/sdk_tests/token_v2_processor_tests.rs
- rust/integration-tests/src/sdk_tests/user_transaction_processor_tests.rs
https://github.com/aptos-labs/aptos-core/commit/9e9194cec8843f5f80f5499ccfa43f44f680728c reflecting this change
> update test transaction dependency

- rust/processor/src/db/postgres/migrations/2025-01-07-000504_add_function_columns_to_user_transactions/up.sql
Query pattern is 
```
SELECT * FROM user_transactions WHERE
entry_function_contract_address = 'xyz'
order_by version
```
> update the index for query perf.

- rust/processor/src/db/postgres/migrations/2025-01-25-000459_drop_storage_id_index/down.sql
- rust/processor/src/db/postgres/migrations/2025-01-25-000459_drop_storage_id_index/up.sql
- rust/sdk-processor/src/steps/fungible_asset_processor/fungible_asset_storer.rs
^
Tested the query drop in testnet.
> [indexer] allow filter FAA table data ingestion. Remove storage_id index.

- rust/Cargo.lock
- rust/Cargo.toml
- rust/integration-tests/sdk_expected_db_output_files/user_transaction_processor/test_single_sender_account_abstraction/signatures.json
- rust/integration-tests/sdk_expected_db_output_files/user_transaction_processor/test_single_sender_account_abstraction/user_transactions.json
- rust/integration-tests/src/sdk_tests/user_transaction_processor_tests.rs
add a test with a testnet aa txn.
> add aa testnet txn test
