- README.md
- python/config.yaml.example
- python/processors/aptos_ambassador_token/processor.py
- python/processors/example_event_processor/models.py
- python/processors/example_event_processor/processor.py
- python/processors/nft_orderbooks/nft_marketplace_activities_processor.py
- python/utils/config.py
- python/utils/transactions_processor.py
- typescript/config.yaml.example
- typescript/processors/example-write-set-change-processor/processor.ts
- typescript/utils/config.ts
This PR does a few things:
1. Fix crashing example processor (verified via docker compose) by adding Mapped[str] to event column names: https://github.com/aptos-labs/aptos-indexer-processors/pull/36/files#diff-a95726e6e182fd11c7bcaf79632ec6d3e8304f33b3f13efe5e3a845a3c299568L20-L21
2. rename config parameters to more clearly distinguish between processor-specific config and config to connect to remote indexer-grpc data stream service.
3. make indexer_name a processor level constant instead of runtime config.
> rename config parameters and make indexer_name a processor-level constant

- python/config.yaml.example
- python/processors/example_event_processor/processor.py
- python/processors/nft_marketplace_v2/processor.py
- python/processors/nft_orderbooks/nft_marketplace_processor.py
- python/utils/config.py
- python/utils/transactions_processor.py
- python/utils/worker.py
* Move a lot of code from TransactionsProcessor to IndexerProcessorServer
* Add multithreading (doing it the same way that Rust does it) 
* I'll optimize db writes later
1. Locally ` poetry run python -m processors.nft_marketplace_v2.processor -c config.yaml`
2. Deployed the nft marketplace v2 processor, and now it's running faster than Rust processors
> [EI-226] Add multithreading to python processor

- rust/processor/src/worker.rs
We added chunking to grpc data service which causes our processors to be very slow. The right thing to do is to rework this logic completely by adding a thread to exclusively fetch from grpc. This is a quick hack to get processors back to speed.
> [rust] hack to speed up processors again

- rust/processor/src/worker.rs
* This happens when starting from version 0, and `last_processed_version` should accept `-1` in this case. 
Tested locally; looks good.
> [indexer processor] fix the underflow.

- python/processors/nft_marketplace_v2/processor.py
* Multithreaded DB writes means that inserting a row  may overwrite newer transaction data already inserted by a different thread. 
* This adds the fix by doing on_conflict_do_update and comparing the last_transaction_version. 
* Also fixes the multithreaded postgres DB lock by sorting by primary key when inserting.
> Support backfill and fix multithreaded inserts

- rust/processor/src/models/token_models/ans_lookup.rs
Token processor is failing due to an unwrap. 
For some reason, this transaction has an event w/ type address https://fullnode.testnet.aptoslabs.com/v1/transactions/by_version/613159168
> [rust] Fix token processor error

- rust/processor/src/worker.rs
The GRPC stream isn't expected to persist forever and it's annoying that things disconnect every 3-4 hours. This adds reconnect feature to the rust processor. We allow max 1 reconnect per minute because anything more would likely indicate that the grpc server itself is broken. 
Note, this will help with the backfill problem but does not fully solve it. (i.e. during backfill if we restart the processor we'll restart from the manually specified starting_version all over again). 
Ran the processor and tested a few cases manually: 
* Kill the grpc data service - observed correctly that reconnection happened
* Kill the grpc data service again - observed correctly that the second time didn't reconnect
* Set starting version and ending version as both 0 and observed that reconnection didn't …
> [Rust] Reconnect max once every minute (configurable in code)

- .gitmodules
Makes it possible to clone this repo with https. This was causing issues with building crates that depend on this repo.
Referring to the code by https is how we normally prefer to do it anyway for git submodules, I imagine for this reason.
Confirmed that this works by updating a project to rely on this branch instead.
> Refer to tontine submodule by https not git

- rust/processor/migrations/2023-08-12-190707_add_ans_is_primary/down.sql
- rust/processor/migrations/2023-08-12-190707_add_ans_is_primary/up.sql
- rust/processor/src/models/ans_models/ans_lookup.rs
- rust/processor/src/models/ans_models/ans_utils.rs
- rust/processor/src/models/ans_models/mod.rs
- rust/processor/src/processors/ans_processor.rs
- rust/processor/src/schema.rs
- rust/processor/src/utils/util.rs
Question: Should we rename the configs to v1? e.g. ans_primary_names_table_handle -> ans_v1_primary_names_table_handle
Main changes
* Logic can be simplified
* No need for lookup if primary names table is keyed on address
* Fix typos
* remove is_primary from ans_lookup tables
* is_primary -> is_deleted in primary name tables
* Code structure
* Extract non critical code to ans_utils
* Moved the table handle checking logic in the functions themselves. It'll allow easier extensibility into v2 and it keeps the main processor flow decluttered.
> Fix schema and clean up code

- rust/processor/migrations/2023-08-14-235438_add_current_delegated_voter_table/down.sql
- rust/processor/migrations/2023-08-14-235438_add_current_delegated_voter_table/up.sql
- rust/processor/src/models/stake_models/current_delegated_voter.rs
- rust/processor/src/models/stake_models/delegator_balances.rs
- rust/processor/src/models/stake_models/stake_utils.rs
- rust/processor/src/processors/stake_processor.rs
- rust/processor/src/schema.rs
Comments about the changes: 
* primary key already adds an index
* in this case it's `PRIMARY KEY (delegation_pool_address, delegator_address)`, which adds an index already on `delegation_poo_address` so we don't need to add it again (basically if pk or index is on `(a, b)`, it creates an index for `a`, then `(a,b)`, you do need to add one for `b` separately if you plan to only query `b`)
* upgrade diesel so that diesel migrations generates the proper schema.rs
* Shouldn't limit to user transactions because some changes might be coming from block metadata changes
* Adopt the PK from @rtso's ANS PR
* Persist mappings across transactions (whenever a look up is needed, we need to also persist mapping thru the full batch)
Tips
* Unindent by assigning variables
* Make sure that models …
> Partial voting review

- rust/processor/migrations/2023-08-22-232603_add_ans_view/down.sql
- rust/processor/migrations/2023-08-22-232603_add_ans_view/up.sql
- rust/processor/src/processors/ans_processor.rs
Update non-`current_` ANS tables to use `do_nothing` on conflict 
Run the processor in testnet locally
> Clean up ANS

- rust/.dockerignore
- rust/Dockerfile
- rust/scripts/build.sh
The previous setup had a few issues:
- Needlessly brought in more context than was necessary because there was no .dockerignore.
- Didn't use two stages, so the image is bigger than necessary.
- Didn't expose the correct health check port by default.
This PR fixes all that.
The image is now only 176 mb instead of a couple of gbs.
```
docker build . -t indexer-processor
```
```
docker run -it --network host --mount type=bind,source=/tmp/config.yaml,target=/config.yaml indexer-processor:latest -c /config.yaml
```
> Fix dockerfile for rust/processor

- rust/processor/src/worker.rs
There are 2 cases where we need to retry connection
1. When response stream returns an error
2. When response stream returns no more items
This PR moves the reconnection logic to account for both cases.
* With ending_version
* Close the GRPC stream and check that it reconnects (TBD)
> [Rust] Improve reconnection logic

- .github/workflows/copy-processor-images-to-dockerhub.yaml
- package.json
- pnpm-lock.yaml
- scripts/release-processor-images.mjs
run 
```
GIT_SHA=656c8bff2fe62c8071fa74784efc81b7c0c3766b GCP_DOCKER_ARTIFACT_PROCESSOR_REPO_US="us-docker.pkg.dev/aptos-registry/docker" ./scripts/release-processor-images.mjs --language=rust --version-tag=fake-version
```
can see new images published to dockerhub
> add workflow to export processor images

- rust/processor/src/worker.rs
* Remove the nested loops
* Add a retry field so that if the upstream server is rebuilding we won't panic. This will potentially create more short lived connections which is something we should watch out for.
* Reduce the reconnect time to 15 seconds from 60. 
Test: I still see restarts in kube. Hopefully no more.
> [Rust] clean up reconnect logic

- .github/workflows/copy-processor-images-to-dockerhub.yaml
- scripts/README.md
- scripts/package.json
- scripts/release-processor-images.mjs
I think installing the pnpm deps from inside the script is a bit irregular. I instead make the script something you just run via a script entry in package.json. I think everyone knows you should run `pnpm install` before running a JS script.
Beyond that, the script was broken, for example the way we were invoking `crane tag` was incorrect. I fix that in this PR.
```
gh workflow run 'Release Processor Images' --ref banool/release-processor-images -f GIT_SHA=de766ae36a1c74212d370aae75bf234320612bbc -f version_tag=v1.0.4
```
> Install pnpm in GH workflow, fix tagging in release-processor-images.mjs

- rust/processor/src/processors/nft_metadata_processor.rs
Collections also have assets that can be added to the CDN. This adds `CurrentCollectionV2` to also be indexed in the NFT Metadata Processor.
> [NFT Metadata Crawler] Add collection support for processor

- rust/processor/migrations/2023-09-01-231248_events_v2/down.sql
- rust/processor/migrations/2023-09-01-231248_events_v2/up.sql
- rust/processor/src/models/default_models/block_metadata_transactions.rs
- rust/processor/src/models/default_models/events.rs
- rust/processor/src/models/default_models/transactions.rs
- rust/processor/src/models/default_models/user_transactions.rs
- rust/processor/src/models/default_models/write_set_changes.rs
- rust/processor/src/processors/default_processor.rs
- rust/processor/src/schema.rs
* Change primary key of events table for v2 (should be just on transaction_version and event index)
* Remove unused query structs
I validated that (transaction_version, event_index) is a valid PK (no duplicates) 
events table works
v2 event works as well
> [Rust] Events v2

- rust/processor/src/processors/nft_metadata_processor.rs
Trim URIs because some contain new lines at the end
> [NFT Metadata Crawler] Add trim to URIs

- rust/processor/src/processors/nft_metadata_processor.rs
Reverts aptos-labs/aptos-indexer-processors#131 to move trimming logic more down stream
> Revert "[NFT Metadata Crawler] Add trim to URIs"

- hasura-api/metadata-json/unified.json
- rust/processor/migrations/2023-09-07-175640_storage_refund/down.sql
- rust/processor/migrations/2023-09-07-175640_storage_refund/up.sql
- rust/processor/src/models/coin_models/coin_activities.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_activities.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_utils.rs
- rust/processor/src/processors/fungible_asset_processor.rs
- rust/processor/src/schema.rs
Add new field to coin and fungible asset activities to indicate storage refund. 
It's not in testnet or mainnet just yet, so using ledger for now
Testnet: 667675894
Mainnet: 255894550
> [Rust] Storage refund

- rust/Dockerfile
- typescript/aptos-indexer-protos/src/aptos/indexer/v1/raw_data.ts
- typescript/aptos-indexer-protos/src/aptos/internal/fullnode/v1/fullnode_data.ts
Update Dockerfile to include `post-processor` binary in the final docker image. `post-processor` binary will be used to deploy it in cloud run.
> Add post-processor to docker build

- rust/processor/src/processors/fungible_asset_processor.rs
- rust/processor/src/worker.rs
* Fix bug where events is 0, we missed gas event for fungible_asset_processor. 
* Also added break when ending_version is specified
Easiest to just backfill from 0.
> [Rust] Handle case of missing gas when events is empty

- rust/post-processor/src/main.rs
- rust/processor/src/main.rs
- rust/server-framework/src/lib.rs
Currently we create a runtime from within the context of a runtime. This is a big no no with tokio and can cause a variety of issues, particularly when using this code from another place: https://stackoverflow.com/q/62536566/3846032.
To address this, instead of creating a runtime in `run_server_with_config`, I require that the caller passes in a handle.
I ran the formatter, linter, tests, and succesfully ran a processor against a txn stream.
> Fix nested runtimes issue with Rust processors

- rust/post-processor/src/main.rs
- rust/processor/src/config.rs
- rust/processor/src/main.rs
- rust/processor/src/utils/database.rs
- rust/processor/src/worker.rs
- rust/server-framework/src/lib.rs
From the CLI I need to be able to run migrations only once due to this problem: https://aptos-org.slack.com/archives/C04PRP1K1FZ/p1695747178956299. This makes it possible.
This is a backwards compatible change re existing configs, they should all work fine as they are now.
I also fix issues with concurrent chain ID updates.
> Make it possible to run migrations separately in the Rust processors

- python/processors/main.py
- python/utils/worker.py
Add reconnection logic to Python processors because the GRPC stream isn't expected to persist forever. 
While testing, I found that the `channel_recv_latency_in_secs` is relatively high and dominates the overall processor performance.
```
INFO:root:{"processor_name": "nft_marketplace_v2_processor", "start_version": "189806000", "end_version": "189806999", "batch_size": "1000", "tps": "1668.5985310137194", "message": "[Parser] Processed transactions"}
INFO:root:{"processor_name": "nft_marketplace_v2_processor", "start_version": "189807000", "end_version": "189807999", "channel_size": 1, "channel_recv_latency_in_secs": "0.69648696", "message": "[Parser] Received chunk of transactions"}
INFO:root:{"processor_name": "nft_marketplace_v2_processor", "task_count": 1, "processing_duration": …
```
> [Python] Add grpc reconnection logic to python processors

- rust/Cargo.lock
- rust/Cargo.toml
- rust/aptos-indexer-protos/Cargo.toml
- rust/processor/src/models/default_models/transactions.rs
- rust/processor/src/models/default_models/write_set_changes.rs
In order to use aptos-indexer-protos in aptos-core we need to make sure the crate versions between the two repos match. This PR does that and makes the appropriate fixes.
I ran a processor with this config:
```
health_check_port: 8084
server_config:
processor_config:
type: default_processor
postgres_connection_string: postgresql://postgres:@localhost:5432/default_processor
indexer_grpc_data_service_address: https://grpc.testnet.aptoslabs.com
auth_token: <token>
```
With this command:
```
cargo run -p processor -- -c ~/config.yaml
```
The processor started up and processed txns successfully.
> [Rust] Update codegen deps

- .github/workflows/build-images.yaml
- .github/workflows/copy-processor-images-to-dockerhub-release.yaml
- .github/workflows/copy-processor-images-to-dockerhub.yaml
- scripts/release-processor-images.mjs
Build:
* on push to new versioned release branches `aptos-indexer-processors-v*`
* on push to new network-specific release branches `aptos-indexer-processors-{devnet,testnet,mainnet}`
Release images to dockerhub:
* on push to new network-specific release branches `aptos-indexer-processors-{devnet,testnet,mainnet}`
* on new git tag(release) version X.Y.Z `aptos-indexer-processors-vX.Y.Z`
> [gha] build and release images based on new branching strategy

- hasura-api/metadata-json/unified.json
- rust/processor/migrations/2023-10-27-030502_event_type/down.sql
- rust/processor/migrations/2023-10-27-030502_event_type/up.sql
- rust/processor/src/models/events_models/events.rs
- rust/processor/src/processors/events_processor.rs
- rust/processor/src/schema.rs
2 changes in this PR
* create a new indexed_type field for events (I couldn't just replace the old one due to a diesel migration bug)
* create spam table
Note that the new field indexed_type field needs to be limited length. I picked 300 b/c that's the current p99 in mainnet. 
We also need to backfill fungible asset fix from https://github.com/aptos-labs/aptos-indexer-processors/pull/167
fungible_asset_processor
testnet: 553151941
mainnet: 199271122
events_processor
testnet: 0
mainnet: 0
new field is indexed
> [rust] Index events type, backfill fungible assets fix, and create spam table

- rust/processor/src/models/default_models/move_modules.rs
- rust/processor/src/processors/ans_processor.rs
- rust/processor/src/processors/nft_metadata_processor.rs
- rust/processor/src/processors/token_v2_processor.rs
- rust/processor/src/worker.rs
Basically we didn't realize that ABI could be empty when uploading a new module. But it is possible. 
No longer crashes
> [rust][fix] Fix move module crash

- hasura-api/metadata-json/README.md
- hasura-api/metadata-json/unified.json
This PR adds the pool settings to the Hasura metadata and sets total_max_connections rather than max_connections. This increases the overall max connections from Hasura to the DB.
Live in prod already.
See here for more info: https://aptos-org.slack.com/archives/C06AP2QT3TM/p1702989622752439?thread_ts=1702982946.408549&cid=C06AP2QT3TM.
> [Hasura] Include pool settings in Hasura metadata

- rust/Cargo.lock
- rust/Cargo.toml
Some of these deps were updated in aptos-core so I'm updating them here too.
CI for now. When we roll out to devnet we'll see if this causes any issues (which I don't expect to happen).
> Update bigdecimal and diesel deps

- rust/processor/migrations/2024-01-11-224315_update_process_status/down.sql
- rust/processor/migrations/2024-01-11-224315_update_process_status/up.sql
- rust/processor/src/models/default_models/move_modules.rs
- rust/processor/src/models/processor_status.rs
- rust/processor/src/models/token_v2_models/v2_token_datas.rs
- rust/processor/src/processors/mod.rs
- rust/processor/src/schema.rs
- rust/processor/src/worker.rs
* This change updates the processor status to include latest transaction timestamp in the table.
> update the processor status.

- rust/processor/migrations/2023-12-15-221028_payload_type/down.sql
- rust/processor/migrations/2023-12-15-221028_payload_type/up.sql
- rust/processor/migrations/2023-12-16-233224_add_objects_model/down.sql
- rust/processor/migrations/2023-12-16-233224_add_objects_model/up.sql
- rust/processor/src/models/account_transaction_models/account_transactions.rs
- rust/processor/src/models/default_models/mod.rs
- rust/processor/src/models/default_models/transactions.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_activities.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_balances.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_utils.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_metadata.rs
- rust/processor/src/models/mod.rs
- rust/processor/src/models/object_models/mod.rs
- rust/processor/src/models/object_models/v2_object_utils.rs
- rust/processor/src/models/object_models/v2_objects.rs
- rust/processor/src/models/token_v2_models/v2_collections.rs
- rust/processor/src/models/token_v2_models/v2_token_activities.rs
- rust/processor/src/models/token_v2_models/v2_token_datas.rs
- rust/processor/src/models/token_v2_models/v2_token_metadata.rs
- rust/processor/src/models/token_v2_models/v2_token_ownerships.rs
- rust/processor/src/models/token_v2_models/v2_token_utils.rs
- rust/processor/src/processors/default_processor.rs
- rust/processor/src/processors/fungible_asset_processor.rs
- rust/processor/src/processors/mod.rs
- rust/processor/src/processors/nft_metadata_processor.rs
- rust/processor/src/processors/objects_processor.rs
- rust/processor/src/processors/token_v2_processor.rs
- rust/processor/src/schema.rs
- rust/processor/src/utils/util.rs
- rust/processor/src/worker.rs
Testnet: genesis
Mainnet: genesis
> Add back payload type

- rust/indexer-metrics/src/main.rs
- rust/indexer-metrics/src/metrics.rs
* Adds e2e latency monitoring for processors. 
* locally tested, looks good.
* Example response
```json
{
"processor_status": [
{
"processor": "objects_processor",
"last_updated": "2024-01-16T21:59:54.425376",
"last_transaction_timestamp": "2024-01-16T21:59:54.425376",
"last_success_version": 853440763
},
{
"processor": "token_v2_processor",
"last_updated": "2024-01-16T21:59:54.407772",
"last_transaction_timestamp": "2024-01-16T21:59:54.407772",
"last_success_version": 853440763
},
{
"processor": "account_transactions_processor",
"last_updated": "2024-01-16T21:59:54.392648",
"last_transaction_timestamp": "2024-01-16T21:59:54.392648",
"last_success_version": 853440763
},
{
"processor": "fungible_asset_processor",
"last_updated": "2024-01-16T21:59:54.40526",
"last_transaction_timestamp": …
```
> add the monitoring piece to the monitoring.

- hasura-api/metadata-json/unified.json
* Add the block timestamp into processor status rest api to monitor the end-2-end latency.
* Tested in Hasura console; looks good.
> add block timestmap into the processor status rest api endpoint.

- rust/processor/src/utils/counters.rs
- rust/processor/src/worker.rs
* Add the latency monitoring observed from processors.
Note: the other latency measurement is not necessary to be accurate since it spilts into chunks and measured within each chunk..
> [monitoring] add the latency observed by processors.

- rust/processor/src/models/user_transactions_models/signatures.rs
- rust/processor/src/processors/mod.rs
- rust/processor/src/processors/monitoring_processor.rs
- rust/processor/src/worker.rs
> Remove panic and fix monitoring processor

- rust/Cargo.lock
- rust/Cargo.toml
- rust/processor/Cargo.toml
- rust/processor/migrations/2023-11-09-234725_delegator_balances_3/up.sql
- rust/processor/src/grpc_stream.rs
- rust/processor/src/main.rs
- rust/processor/src/processors/mod.rs
- rust/processor/src/utils/counters.rs
- rust/processor/src/utils/database.rs
- rust/processor/src/worker.rs
instead of waiting for the grpc fetch batch to complete, and then the workers to complete, this passes each grpc fetch directly to a worker thread
> Change threading model for higher parallelism and throughput

- rust/processor/src/processors/account_transactions_processor.rs
- rust/processor/src/processors/ans_processor.rs
- rust/processor/src/processors/coin_processor.rs
- rust/processor/src/processors/default_processor.rs
- rust/processor/src/processors/events_processor.rs
- rust/processor/src/processors/fungible_asset_processor.rs
- rust/processor/src/processors/mod.rs
- rust/processor/src/processors/objects_processor.rs
- rust/processor/src/processors/stake_processor.rs
- rust/processor/src/processors/token_processor.rs
- rust/processor/src/processors/token_v2_processor.rs
- rust/processor/src/processors/user_transaction_processor.rs
- rust/processor/src/utils/database.rs
- rust/processor/src/worker.rs
small theoretical performance gain, but mainly in preparation for a world of parallelism, so each sub-task is able to pull from the DB pool whenever it needs a connection, instead of re-using the same one
> Pass around DB pools instead of holding connections for long periods

- rust/Cargo.lock
- rust/Cargo.toml
- rust/processor/Cargo.toml
- rust/processor/src/grpc_stream.rs
- rust/processor/src/models/default_models/write_set_changes.rs
- rust/processor/src/worker.rs
kanal has higher performance than the tokio MPSC channels in benchmarks, and this sets us up for the next set of PRs utilizing kanal for parallelism
Testing:
Ran locally; saw indexing continued to work
> Use Kanal for async channels

- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_activities.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_balances.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_metadata.rs
- rust/processor/src/models/object_models/v2_objects.rs
- rust/processor/src/models/token_v2_models/v2_collections.rs
- rust/processor/src/models/token_v2_models/v2_token_activities.rs
- rust/processor/src/models/token_v2_models/v2_token_datas.rs
- rust/processor/src/models/token_v2_models/v2_token_metadata.rs
- rust/processor/src/models/token_v2_models/v2_token_ownerships.rs
* Update the fungible asset and token v2 processors to query for whether an object is token and/or fungible asset using the current_objects table 
* Also use ObjectAggregatedDataMapping everywhere instead of TokenV2DataMapping or FungibleAssetMetadataMapping
* Dependent on this PR: https://github.com/aptos-labs/aptos-indexer-processors/pull/215
* If you're running fungible asset processor or token v2 processor, you must also run objects processor to lookup object data
* Testnet: Backfill objects processor
```
server_config:
processor_config:
type: "objects_processor"
starting_version: 469526272
```
* Mainnet: Backfill objects processor
```
server_config:
processor_config:
type: "objects_processor"
starting_version: 144201952
```
Run token v2 processor starting_version = 803795000 (when …
> Update fungible asset and token processor queries to use objects table

- rust/Cargo.lock
- rust/Cargo.toml
- rust/processor/migrations/2024-02-16-234847_any_signature/down.sql
- rust/processor/migrations/2024-02-16-234847_any_signature/up.sql
- rust/processor/src/models/default_models/transactions.rs
- rust/processor/src/models/user_transactions_models/signatures.rs
- rust/processor/src/schema.rs
- rust/processor/src/utils/util.rs
https://github.com/aptos-labs/aptos-core/releases/tag/aptos-indexer-grpc-v1.4.0
Add new validator transaction handling and change signature parsing
also remove ModuleBundlePayload b/c protobuf doesn't support anymore. 
None
in case of an unknown transaction
yay! it works for new types
> upgrade processor to grpc 1.4 (node 1.10)

- rust/processor/README.md
- rust/processor/src/config.rs
- rust/processor/src/grpc_stream.rs
- rust/processor/src/lib.rs
- rust/processor/src/processors/mod.rs
- rust/processor/src/transaction_filter.rs
- rust/processor/src/utils/counters.rs
- rust/processor/src/worker.rs
Allow filtering transactions that reach the processor right after GRPC via config
The criteria are combined with `AND`, if a criteria is not set, it is ignored
adds a config section:
```
server_config:
transaction_filter:
focus_contract_addresses:
- "0x0"
skip_sender_addresses:
- "0x0"
focus_user_transactions: true
```
> Introduce txn filter

- rust/processor/src/config.rs
- rust/processor/src/transaction_filter.rs
Make config work even when `TransactionFilter` is not there
> default for TransactionFilter config

- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_balances.rs
- rust/processor/src/models/object_models/v2_objects.rs
- rust/processor/src/processors/objects_processor.rs
* Use the correct metadata address to lookup whether an object is a fungible asset
* Fix current_object is_fungible_asset to check for existence of FungibleAssetMetadata, not FungibleAssetStore
https://explorer.aptoslabs.com/txn/313811207/userTxnOverview?network=mainnet
Run objects_processor with version 313811207. See that is_fungible_asset is true. 
Run fungible_asset_processor with version 313811207. Fungible asset store is indexed
> Fix fungible asset metadata

- rust/Cargo.lock
- rust/Cargo.toml
- rust/processor/Cargo.toml
- rust/processor/src/config.rs
- rust/processor/src/gap_detector.rs
- rust/processor/src/grpc_stream.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_utils.rs
- rust/processor/src/models/token_v2_models/v2_token_datas.rs
- rust/processor/src/models/token_v2_models/v2_token_ownerships.rs
- rust/processor/src/processors/account_transactions_processor.rs
- rust/processor/src/processors/ans_processor.rs
- rust/processor/src/processors/coin_processor.rs
- rust/processor/src/processors/default_processor.rs
- rust/processor/src/processors/events_processor.rs
- rust/processor/src/processors/fungible_asset_processor.rs
- rust/processor/src/processors/mod.rs
- rust/processor/src/processors/monitoring_processor.rs
- rust/processor/src/processors/nft_metadata_processor.rs
- rust/processor/src/processors/objects_processor.rs
- rust/processor/src/processors/stake_processor.rs
- rust/processor/src/processors/token_processor.rs
- rust/processor/src/processors/token_v2_processor.rs
- rust/processor/src/processors/transaction_metadata_processor.rs
- rust/processor/src/processors/user_transaction_processor.rs
- rust/processor/src/utils/counters.rs
- rust/processor/src/utils/database.rs
- rust/processor/src/worker.rs
Changes the logic to fetch in batches and throw them into a channel, as before, but no longer worrying about ordering
There are a number of tasks spawned equal to `number_concurrent_processing_tasks` that are launched, each with their own processor instance, which pull directly from the fetched pb channel
Each block of fetched transactions is processed in parallel. Local testing saw 1-2.5k TPS per task 
Next is parallel insertion on the DB side, in much smaller batches
It may make sense to move the pb fetcher to it's own OS thread given how critical it is, and how easy it is to starve otherwise
Will be tested via devnet load test
> Process with parallelism

- rust/processor/migrations/2024-03-07-224504_fungible_asset_metadata_is_token_v2/down.sql
- rust/processor/migrations/2024-03-07-224504_fungible_asset_metadata_is_token_v2/up.sql
- rust/processor/src/models/fungible_asset_models/v2_fungible_metadata.rs
- rust/processor/src/models/object_models/v2_objects.rs
- rust/processor/src/models/token_v2_models/v2_token_datas.rs
- rust/processor/src/processors/objects_processor.rs
- rust/processor/src/schema.rs
To improve dev ex, we remove the dependency of token v2 / fungible asset processor on objects processor. 
In `fungible_asset_metadata`, introduce a column `is_token_v2`. Fungible asset processor will lookup `is_token_v2` to skip indexing fungible tokens. 
Token v2 processor will lookup `current_token_datas_v2.is_fungible_v2` to index the fungible token. 
Fungible token with metadata in same txn. https://explorer.aptoslabs.com/txn/351790067/userTxnOverview?network=mainnet
See that the fungible token is indexed in the tokens table and not the fungible balances table. 
Normal fungible asset indexing still works
Normal token indexing still works
Objects indexing still works
> Remove dependency on objects processor

- rust/processor/src/models/fungible_asset_models/v2_fungible_metadata.rs
- rust/processor/src/processors/fungible_asset_processor.rs
The logic was wrongly excluding fungible asset, also didn't backfill is_token column properly. 
Confirm that it overrides the old field
Also that the reported cellana issue for transaction 490148488 is cleared
> [hotfix] Fix fungible asset logic

- rust/processor/src/processors/coin_processor.rs
Fixes the "inset" typo in `inset_coin_supply_query`
> Fix typo: inset -> insert

- rust/processor/src/models/user_transactions_models/signatures.rs
We changed parsing for signature in 1.10 so this makes sure that we handle both not just the new one. 
None
Before
After
> [rust] making signatures backward compatible

- rust/processor/src/models/token_v2_models/v2_token_ownerships.rs
- rust/processor/src/processors/token_v2_processor.rs
This closes the loop on the messy logic that is burning NFTs: 
There could be a complete burn or a partial burn.
* In the complete burn case, we don’t have anything so we either have the previous_owner field from the new burn event, or have to do a db lookup
* In the partial burn case, we assumed (wrongly) that ObjectCore will be there.
This PR fixes the partial burn case. 
First burn event 
Testnet: 835574507
Mainnet: 151521169
NFT burnt!
> [rust] handle burn properly for partial burns

- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_activities.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_balances.rs
If coin type is too long so we’re not tracking it under the new logic (> 1K length). But the lookup logic was still there so it caused some issues. 
This skips cases where the mapping isn't there. 
Also this only applies to coin v1.
No longer panics
> [hotfix] fix panic where coin type is too long

- .github/actions/protobuf-compatibility-check/action.yaml
- .github/workflows/check-protobuf-compatibility.yaml
- .github/workflows/nightly-check-protobuf-compatibility.yaml
* Goal: if new `enum` variant or `oneof` field is added, this check will break. 
* The data quality/correctness will be checked separately. 
When new enum variant or oneof field is added, workflow failure:
> Compatibility Check Workflow

- rust/Dockerfile
* This change is to use native git client to fetch git dependencies for rust processor.
* built-in git client may not be resilient to network errors.
> make cargo build robust to network failure for git dependencies.

- python/utils/worker.py
For python processor, some versions are causing deserialization error. The hunch is that the transaction has deeply nested types and the python grpc library runs into recursion error when trying to deserialize these types. The workaround is to skip the batch in processing. 
Run python nft marketplace processor starting from version 560868370 and verify that it skips up to version 560868374 (the offending version)
> [python] Skip versions that can't be deserialized

- .github/workflows/lint.yaml
- rust/Cargo.lock
- rust/Cargo.toml
- rust/Dockerfile
- rust/server-framework/Cargo.toml
- rust/server-framework/src/lib.rs
Serves the CPU flamegraph at "host:health_check_port/profilez" page.
It took 10s to collect samples, and you will see the flamegraph afterwards.
> Add CPU profiling support.

- rust/processor/src/models/coin_models/coin_utils.rs
Currently, the regular expression is compiled anew with each iteration of the loop. This compilation process is resource-intensive, and there's no built-in caching mechanism. Consider utilizing lazy_static to cache the compiled result for optimization.
> coin_processor optimization: compile regex once

- rust/processor/src/config.rs
- rust/processor/src/grpc_stream.rs
- rust/processor/src/worker.rs
When updating grpc image, we observe some processor reconnection hangs when making the grpc request. Example where processor hangs for 2 mins ([link](https://cloud.us.humio.com/k8s/search?columns=%5B%7B%22type%22%3A%22field%22%2C%22fieldName%22%3A%22%40timestamp%22%2C%22format%22%3A%22datetime%22%2C%22width%22%3A180%7D%2C%7B%22type%22%3A%22field%22%2C%22fieldName%22%3A%22level%22%2C%22format%22%3A%22text%22%2C%22width%22%3A54%7D%2C%7B%22type%22%3A%22link%22%2C%22openInNewBrowserTab%22%3Atrue%2C%22style%22%3A%22button%22%2C%22hrefTemplate%22%3A%22https%3A%2F%2Fgithub.com%2Faptos-labs%2Faptos-core%2Fpull%2F%7B%7Bfields%5B%5C%22github_pr%5C%22%5D%7D%7D%22%2C%22textTemplate%22%3A%22%7B%7Bfields%5B%5C%22github_pr%5C%22%5D%7D%7D%22%2C%22header%22%3A%22Forge%20PR%22%2C%22width%22%3A79%7D%2C%7B%22 …
> [EI-370] Timeout if grpc request takes too long

- rust/processor/migrations/2024-04-18-173631_fungible_token/down.sql
- rust/processor/migrations/2024-04-18-173631_fungible_token/up.sql
- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_activities.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_balances.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_metadata.rs
- rust/processor/src/models/object_models/v2_object_utils.rs
- rust/processor/src/models/token_v2_models/v2_token_activities.rs
- rust/processor/src/models/token_v2_models/v2_token_datas.rs
- rust/processor/src/models/token_v2_models/v2_token_ownerships.rs
- rust/processor/src/processors/fungible_asset_processor.rs
- rust/processor/src/processors/token_v2_processor.rs
- rust/processor/src/schema.rs
- test_move_script/Move.toml
- test_move_script/README.md
- test_move_script/sources/modules/managed_fungible_asset.move
- test_move_script/sources/run_script.move
- test_move_script/sources/scripts/burn_fungible_token.move
- test_move_script/sources/scripts/fungible_token.move
- test_move_script/sources/scripts/transfer_fungible_token.move
Index fungible assets and tokens independently, to better reflect the composable nature of the object model on chain
1. Add fungible-related columns `maximum_v2` and `supply_v2` to `fungible_asset_metadata` (copied from `current_token_datas_v2` )
1. For coins, these fields will be null
2. Set to null fungible-related columns `maximum`, `supply`, `decimals` from `token_datas_v2`
1. The only place that tracks fungibility of a token will be in `current_token_datas_v2.is_fungible_v2`
3. Set to null these columns since we can use a join to get the same information. 
- `fungible_asset_metadata.is_token_v2`
- `token_activities_v2.is_fungible_v2`
- `current_token_ownerships_v2.is_fungible_v2`
- `token_ownerships_v2.is_fungible_v2`
Proposal: …
> [EI-397] Separate fungible asset and token indexing

- rust/processor/src/processors/fungible_asset_processor.rs
- rust/processor/src/processors/token_v2_processor.rs
Fix token v2 and fa current_ table upserts
Backfill
Testnet: 553151941
Mainnet: 199271122
> Fix current inserts

- rust/processor/src/utils/database.rs
> indexer remove weird chunk logic

- rust/moving-average/src/lib.rs
- rust/processor/src/grpc_stream.rs
- rust/processor/src/worker.rs
* Fix the TPS calculation
1. GRPC TPS is off by 1000.
2. use ceiling to avoid loss of accuracy because of truncate.
> Fix TPS calculation

- python/processors/nft_orderbooks/parsers/okx_parser.py
- rust/processor/src/models/coin_models/coin_activities.rs
- rust/processor/src/models/coin_models/coin_utils.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_activities.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_utils.rs
- rust/processor/src/models/mod.rs
- rust/processor/src/models/stake_models/delegator_activities.rs
- rust/processor/src/models/stake_models/proposal_votes.rs
- rust/processor/src/models/stake_models/stake_utils.rs
- rust/processor/src/models/token_models/token_utils.rs
- rust/processor/src/models/token_v2_models/v2_token_utils.rs
- rust/processor/src/processors/fungible_asset_processor.rs
- rust/processor/src/processors/token_v2_processor.rs
In this PR we add event v2 migration indexing support.
PRs to handle:
1. https://github.com/aptos-labs/aptos-core/pull/10532
2. https://github.com/aptos-labs/aptos-core/pull/11688
3. https://github.com/aptos-labs/aptos-core/pull/13147
* V1 + V2: means dedupe is required
* only V1 or V2: means no dedupe is required due to no double emission.
| Module            | Event Name                        | Migration Note          |
| ----------------- | --------------------------------- | ----------------------- |
| account           | KeyRotation                       | not indexed             |
| aptos_account     | DirectCoinTransferConfigUpdated   | not indexed             |
| coin              | Deposit                           | only V1 or V2; not both |
|                   | Withdraw …
> [event_v2] indexer logic update to handle migration 

- rust/processor/migrations/2024-05-17-215042_token_datas_burn_2/down.sql
- rust/processor/migrations/2024-05-17-215042_token_datas_burn_2/up.sql
- rust/processor/src/models/token_v2_models/v2_token_datas.rs
- rust/processor/src/schema.rs
is_deleted_v2 will always be null in this table but just for schema consistency for analytics.
> add is_deleted_v2 to token_datas_v2

- rust/Cargo.lock
- rust/processor/src/grpc_stream.rs
- rust/processor/src/worker.rs
- rust/server-framework/src/lib.rs
Two changes:
1. Auto reconnect to grpc if it times out waiting for txn's from channel. Moving the timeout out of the processor thread to the fetcher loop thread.
2. When processor reaches ending version, it stops gracefully instead of panic
Happy path still works. 
Processor with auto-reconnection
Processor with ending version
Panics in the fetcher thread works.
Panic in processor thread works.
> [EI-428] Auto reconnect grpc if txn stream times out waiting for response

- python/processors/nft_orderbooks/parsers/okx_parser.py
- rust/processor/src/models/coin_models/coin_activities.rs
- rust/processor/src/models/coin_models/coin_utils.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_activities.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_utils.rs
- rust/processor/src/models/mod.rs
- rust/processor/src/models/stake_models/delegator_activities.rs
- rust/processor/src/models/stake_models/proposal_votes.rs
- rust/processor/src/models/stake_models/stake_utils.rs
- rust/processor/src/models/token_models/token_utils.rs
- rust/processor/src/models/token_v2_models/v2_token_utils.rs
- rust/processor/src/processors/fungible_asset_processor.rs
- rust/processor/src/processors/token_v2_processor.rs
This reverts commit 3551f406fe61d53290af6f422a1733ef15a047cd.
This breaks the indexing, here is the example https://explorer.aptoslabs.com/txn/612524417/events?network=mainnet
looks good now.
> Revert "[event_v2] indexer logic update to handle migration (#360)"

- rust/indexer-metrics/src/main.rs
- rust/indexer-metrics/src/util.rs
API Gateway doesn't proxy the REST endpoints for Hasura. We spoke a while ago and decided we'd just not use them. This PR makes that the case.
```
$ cat /tmp/config.yaml
health_check_port: 8080
server_config:
chain_name: testnet
hasura_graphql_endpoint: https://api.testnet.aptoslabs.com/v1/graphql
fullnode_rest_api_endpoint: https://api.testnet.aptoslabs.com/v1
```
```
cargo run -p indexer-metrics -- -c config.yaml
```
Output: https://gist.github.com/banool/c9ead808cba82ece5689a26fa6abd7cf.
See the internal-ops half of this: https://github.com/aptos-labs/internal-ops/pull/3265.
> Use GraphQL rather than REST for indexer-metrics

- rust/Cargo.lock
- rust/Cargo.toml
- rust/processor/Cargo.toml
- rust/processor/migrations/2024-05-04-025823_current_unified_fungible_asset_balance/down.sql
- rust/processor/migrations/2024-05-04-025823_current_unified_fungible_asset_balance/up.sql
- rust/processor/src/models/ans_models/ans_utils.rs
- rust/processor/src/models/coin_models/coin_activities.rs
- rust/processor/src/models/coin_models/coin_supply.rs
- rust/processor/src/models/coin_models/coin_utils.rs
- rust/processor/src/models/default_models/move_resources.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_balances.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_utils.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_metadata.rs
- rust/processor/src/models/object_models/v2_object_utils.rs
- rust/processor/src/models/stake_models/stake_utils.rs
- rust/processor/src/models/token_models/tokens.rs
- rust/processor/src/models/token_v2_models/v2_collections.rs
- rust/processor/src/models/token_v2_models/v2_token_utils.rs
- rust/processor/src/processors/coin_processor.rs
- rust/processor/src/processors/fungible_asset_processor.rs
- rust/processor/src/schema.rs
- rust/processor/src/utils/util.rs
Add a new table `current_unified_fungible_asset_balances` to reflect the total balance of a coin.
tested locally with devnet data:
Just make sure for every step in  [[Correctness Testing](https://www.notion.so/aptoslabs/Testing-Plan-f3f66e05e7e244258a292ad95a80b6e7#3f60ed580c9346dbad35522bbb72ce1a)  the `current_unifed_fungible_asset_balances` table shows the correct number at the correct row&col, which matches `current_coin_balances` and `current_fungible_asset_balances`.
This is the final state on devnet with running fungible asset processor locally.
Row #1 (Shows as column here for better layout) is the default profile APT balance
Row #2 (Shows as column here for better layout) is the test profile APT balance
Row #3 (Shows as column here for better layout) is the default profile …
> [index] current unified balances

- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_balances.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_asset_utils.rs
- rust/processor/src/models/fungible_asset_models/v2_fungible_metadata.rs
- rust/processor/src/models/object_models/v2_object_utils.rs
- rust/processor/src/models/token_v2_models/v2_token_utils.rs
- rust/processor/src/processors/fungible_asset_processor.rs
- rust/processor/src/processors/nft_metadata_processor.rs
- rust/processor/src/processors/objects_processor.rs
- rust/processor/src/utils/util.rs
This PR adds the indexer support for the AIP 70 (https://github.com/aptos-labs/aptos-core/pull/11183).
AIP 70 adds ConcurrentSupply and ConcurrentBalance for fungible assets. Unlike the regular supply and balance, the newly added ConcurrentSupply and ConcurrentBalance use aggregators for improved parallelizability.
This PR indexes ConcurrentSupply and ConcurrentBalance in the indexer. The indexing is done in a way that Supply and ConcurrentSupply, Balance and  ConcurrentBalance are treated identically when storing into the database so that the indexer client wouldn't notice a difference whether the aggregators are being used or not.
> Add ConcurrentFungibleAssetSupply and ConcurrentFungibleAssetBalance

- rust/processor/src/models/coin_models/coin_activities.rs
- rust/processor/src/processors/coin_processor.rs
- rust/processor/src/processors/fungible_asset_processor.rs
As part of the v1 tables and processors migration, we will be deprecating coin_processor. However we still need the coin_supply table, so in this PR we move the table indexing to fungible_asset_processor.
> [EI-463] Move coin supply to fa processor

- rust/processor/migrations/2024-05-21-221101_add_royalty_v1/down.sql
- rust/processor/migrations/2024-05-21-221101_add_royalty_v1/up.sql
- rust/processor/src/models/token_v2_models/mod.rs
- rust/processor/src/models/token_v2_models/v1_token_royalty.rs
- rust/processor/src/models/token_v2_models/v2_token_royalty.rs
- rust/processor/src/processors/token_v2_processor.rs
- rust/processor/src/schema.rs
* Separate royalty to`current_token_royalty_v1` table (note that v2 royalty requires collection id which isn't currently supported in this PR)
* Move the indexing to `token_v2_processor`
Testnet: 0
Mainnet: 0
Mainnet transaction 613858541
> [EI-461] Index royalty in royalty tables

- rust/processor/src/db/common/models/fungible_asset_models/v2_fungible_asset_balances.rs
- rust/processor/src/db/common/models/object_models/v2_object_utils.rs
- rust/processor/src/db/common/models/object_models/v2_objects.rs
- rust/processor/src/db/common/models/token_v2_models/v2_token_ownerships.rs
- rust/processor/src/db/common/models/token_v2_models/v2_token_utils.rs
- rust/processor/src/db/postgres/migrations/2024-06-13-061711_untransferrable/down.sql
- rust/processor/src/db/postgres/migrations/2024-06-13-061711_untransferrable/up.sql
- rust/processor/src/db/postgres/schema.rs
- rust/processor/src/processors/fungible_asset_processor.rs
- rust/processor/src/processors/nft_metadata_processor.rs
- rust/processor/src/processors/objects_processor.rs
- rust/processor/src/processors/token_v2_processor.rs
Handling this AIP https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-83.md
Basically if an object is created with Untransferable resource then it cannot be transferred by anyone including the creator/admin. This PR addresses 3 changes in the indexer
1. Objects -> untransferrable got added
1. Token ownerships v2 -> is_soulbound is true if we see this object. non_transferrable_by_owner is still the old logic (!object_core.allow_ungated_transfer)
Note, we're not doing anything on the fungible asset front since is_frozen is not affected and there's nothing on store level transferrability currently. 
Not actually required if upgrading on time. Otherwise, need to upgrade objects_processor, and token_v2_processor
* Testnet: 1231301072
* Mainnet: 979865558
Obj: …
> [release][aip-83][1.13] Add untransferable handling for FA and token

- rust/processor/src/db/common/models/fungible_asset_models/v2_fungible_asset_balances.rs
- rust/processor/src/db/postgres/migrations/2024-06-13-065302_current_unified_fungible_asset_balance_edit/down.sql
- rust/processor/src/db/postgres/migrations/2024-06-13-065302_current_unified_fungible_asset_balance_edit/up.sql
- rust/processor/src/db/postgres/schema.rs
- rust/processor/src/processors/fungible_asset_processor.rs
* Rename current_unified_fungible_asset_balances -> current_unified_fungible_asset_balances_to_be_renamed
* Set asset_type -> asset_type_v2 (and make it nullable), coin_type -> asset_type_v1
* Create a new asset_type generated from coalesce(asset_type_v2, asset_type_v1). This way all 3 options are covered
* asset not migrated yet: asset_type = asset_type_v1
* before, this would break because the new asset doesn't exist yet so the joins would not work.
* asset migrated: asset_type = asset_type_v2
* asset created with v2: asset_type = asset_type_v2
fungible_asset_processor only
* Testnet: 553151941
* Mainnet: 199271122
Need to test all 3 cases and try to join with fungible_asset_metadata: 
* asset not migrated yet:
* asset migrated:
* asset created with v2:
> Modify current_unified_fungible_asset_balances for smoother migration later

- rust/processor/src/config.rs
Add default to value. Confirmed that this doesn't break even when config is missing.
> maintain backward compatibility

- rust/processor/src/db/postgres/migrations/2024-05-22-200847_add_v1_migration_views/up.sql
These indices are expensive so we comment them out. Running them as concurrently breaks diesel migration.
> comment out expensive indices

- rust/processor/src/processors/objects_processor.rs
This isn't a big issue b/c
1. feature not used yet
2. once object is untrasferrable it can't be changed
> [fix] override untransferrable upon update

- hasura-api/metadata-json/unified.json
* Move resources is now the new view
* unified FA has same configuration as current fa balances
test
https://cloud.hasura.io/public/graphiql?endpoint=https%3A%2F%2Findexer.mainnet.aptoslabs.com%2Fv1%2Fgraphql&query=query+MyQuery+%7B%0A++current_unified_fungible_asset_balances_to_be_renamed%28limit%3A+1%29+%7B%0A++++amount%0A++++asset_type%0A++++is_frozen%0A++++is_primary%0A++++last_transaction_timestamp%0A++++last_transaction_version%0A++++owner_address%0A++++storage_id%0A++++metadata+%7B%0A++++++name%0A++++%7D%0A++%7D%0A%7D%0A
> [metadata] migrate move_resources and add unified fa table

- .github/actions/protobuf-compatibility-check/action.yaml
- rust/Cargo.lock
- rust/Cargo.toml
- rust/processor/src/db/common/models/default_models/transactions.rs
* Add support to new transaction type `BlockEpilogueTransaction`, in details:
* new transaction is indexed under `Transactions` table
* Transaction data will not be indexed in any table, i.e.,
* fields will be ignored.  
```
"block_end_info": {
"block_gas_limit_reached": false,
"block_output_limit_reached": false,
"block_effective_block_gas_units": 0,
"block_approx_output_size": 1244
},
```   
* update the dependency to use a tagged version
> processor proto update.

- rust/processor/src/utils/util.rs
bug: https://aptos-org.slack.com/archives/C03MN5F7WUV/p1718806535035359 
we weren't returning the string in the match statement
Test plan
> fix a bug not returning entry function id for multisig

- .github/workflows/lint.yaml
We have tests defined but we don't actually run them in CI. Let's do that. Fortunately they all still pass.
> Run Rust tests in CI

- rust/processor/src/utils/util.rs
With txn filtering, it's possible that the response txn has no payload or signature. This PR handles that
Run token_v2_processor, token_processor, and user_transaction_processor locally and they works.
> Handle no payload

- rust/processor/src/db/common/models/coin_models/coin_activities.rs
Run coin and fungible asset processor
> Handle no signature/entry function id in coin and fungible processor

- rust/processor/src/processors/default_processor.rs
- rust/processor/src/worker.rs
Add a db skip flag for table items 
tested locally when only skip table_items
> add table_items to deprecated table flag

- rust/processor/src/db/common/models/token_models/nft_points.rs
Handle no entry function id in coin processor
tested locally. 
version used: 51224660
> fix token processor

- rust/processor/src/gap_detectors/mod.rs
processor status wasn't being updated. 
###Test Plan
tested locally
> fix gap detector to update status

- rust/parquet-bq-scripts/table_items_create.sql
- rust/parquet-bq-scripts/table_items_merge.sql
These are the scripts that will be used to load table_item parquet files in GCS buckets into BigQuery.
> add sql scripts for table items bq load

- rust/processor/src/db/postgres/migrations/2024-06-26-220144_add_token_standard/down.sql
- rust/processor/src/db/postgres/migrations/2024-06-26-220144_add_token_standard/up.sql
- rust/processor/src/db/postgres/schema.rs
Adding a generated column for backwards compatibility with `current_fungible_asset_balances`
Run fungible_asset_processor
> Generated token standard column

- rust/processor/src/db/common/models/token_models/token_claims.rs
- rust/processor/src/db/common/models/token_models/tokens.rs
- rust/processor/src/db/common/models/token_v2_models/v2_token_metadata.rs
- rust/processor/src/db/common/models/token_v2_models/v2_token_ownerships.rs
- rust/processor/src/processors/token_processor.rs
- rust/processor/src/processors/token_v2_processor.rs
As part of the V1 table deprecation, we will be deprecating token_processor. However, there is no replacement table for `current_token_pending_claims`, so we move this table to token_v2 processor
> move current_token_pending_claims to token_v2 processor

- rust/processor/src/db/postgres/migrations/2024-06-27-213336_add_v1_migration_view/down.sql
- rust/processor/src/db/postgres/migrations/2024-06-27-213336_add_v1_migration_view/up.sql
As part of the V1 table deprecation, replace the v1 table with view using the v2 table
> create migration view for current_collection_datas

- rust/processor/src/db/common/models/token_v2_models/v2_collections.rs
- rust/processor/src/db/postgres/migrations/2024-07-01-204112_add_collection_properties_to_collections/down.sql
- rust/processor/src/db/postgres/migrations/2024-07-01-204112_add_collection_properties_to_collections/up.sql
- rust/processor/src/db/postgres/schema.rs
- rust/processor/src/processors/token_v2_processor.rs
backfill:
testnet: 18589
mainnet: 169280
> add property maps indexing to collections v2

- rust/processor/src/bq_analytics/gcs_handler.rs
- rust/processor/src/bq_analytics/generic_parquet_processor.rs
- rust/processor/src/bq_analytics/parquet_handler.rs
- rust/processor/src/db/common/models/default_models/parquet_move_resources.rs
- rust/processor/src/db/common/models/default_models/parquet_move_tables.rs
- rust/processor/src/db/common/models/default_models/parquet_transactions.rs
- rust/processor/src/db/common/models/default_models/parquet_write_set_changes.rs
- rust/processor/src/db/common/models/default_models/write_set_changes.rs
- rust/processor/src/db/common/models/fungible_asset_models/v2_fungible_asset_balances.rs
- rust/processor/src/gap_detectors/gap_detector.rs
- rust/processor/src/gap_detectors/mod.rs
- rust/processor/src/gap_detectors/parquet_gap_detector.rs
- rust/processor/src/processors/parquet_default_processor.rs
- rust/processor/src/utils/util.rs
- rust/processor/src/worker.rs
- made bucket root to be configurable for each stage.
- fix gap detector issue where the parquet gap detector wasn't updating its processor status to db.
- move unrelated functions in MoveResource to outside of the struct impl
- removed unnecessary fields in the parquetProcessingResult
Tested locally and verified status being updated
> use option to replace expect with context and avoid creating two gap detectors

- rust/processor/src/db/common/models/fungible_asset_models/v2_fungible_asset_activities.rs
- rust/processor/src/db/common/models/fungible_asset_models/v2_fungible_asset_utils.rs
- rust/processor/src/db/postgres/migrations/2024-07-10-203513_make_asset_type_nullable/down.sql
- rust/processor/src/db/postgres/migrations/2024-07-10-203513_make_asset_type_nullable/up.sql
- rust/processor/src/db/postgres/schema.rs
When a secondary store gets burnt, a Withdraw event gets emitted with storage_id, but there is no corresponding write resource for that storage_id. This PR makes FA processor handle when the store or object gets burnt. In that case, the asset_type and/or owner_address is null.
Backfill versions
Testnet: 1190460551
Mainnet: 954163484
https://explorer.aptoslabs.com/txn/4462417704?network=testnet
> Fix fa indexing when secondary store gets burnt 

- rust/processor/src/db/postgres/migrations/2024-07-08-182507_truncate_deprecated_tables/down.sql
- rust/processor/src/db/postgres/migrations/2024-07-08-182507_truncate_deprecated_tables/up.sql
We stopped writing to move_resources, write_set_changes, and transactions tables, and migrated over to parquet. and we almost reached our alloydb quota, this is to free some spaces.
locally tested
> truncate deprecated tables

- rust/processor/src/db/common/models/default_models/mod.rs
- rust/processor/src/db/common/models/default_models/parquet_move_modules.rs
- rust/processor/src/db/common/models/default_models/parquet_move_tables.rs
- rust/processor/src/db/common/models/default_models/parquet_transactions.rs
- rust/processor/src/db/common/models/default_models/parquet_write_set_changes.rs
- rust/processor/src/processors/parquet_processors/mod.rs
- rust/processor/src/processors/parquet_processors/parquet_default_processor.rs
1. add write_set_size_info to write_set_changes
2. Add txn size info to transaction model
3. migrate move_modules, and table_metadata
tested locally
txn_total_bytes column added to transaction table
table_items table
table_metadata table in testnet
write_set_size info added to write_ste_changes table
move_modules
> Add tranche 2 default model to Parquet 

- rust/Cargo.lock
- rust/Cargo.toml
- rust/processor/src/db/common/models/account_transaction_models/account_transactions.rs
- rust/processor/src/db/common/models/default_models/parquet_transactions.rs
- rust/processor/src/db/common/models/default_models/transactions.rs
- rust/processor/src/db/common/models/stake_models/delegator_activities.rs
- rust/processor/src/processors/events_processor.rs
- rust/processor/src/processors/fungible_asset_processor.rs
* This is to supports events from validator transactions with events migrated from BlockMetadataTransaction.
* First validator transaction in mainnet: 554229017
* First validator transaction in testnet: 942054324
Tested in devnet and looks good.
> [Validator API Fix]support validator txn with its events.

- rust/processor/src/db/common/models/default_models/parquet_transactions.rs
- rust/processor/src/db/common/models/default_models/parquet_write_set_changes.rs
- The rootcause of the failure is from wrong mapping between write_set_changes and WriteSetOpSizeInfo, where write_set_size_info is per state_key_hash not per changes
- synced with the team offline, and we are aligned on having a separate table to close this tranche 2. 
deployed on testnet
> Fix parquet default processor

- rust/processor/src/db/common/models/default_models/parquet_transactions.rs
Fix a bug with txn payload filtering: 
```
│       Message:   mber":126,"threadName":"tokio-runtime-worker","threadId":"ThreadId(41)"}                                                                                                                                                                                   │
│ details = """                                                                                                                                                                                                                                                               │
│ panicked at processor/src/db/common/models/default_models/parquet_transactions.rs:196:22: …
```
> fix payload filtering for parquet processor

- rust/processor/src/bq_analytics/gcs_handler.rs
- rust/processor/src/bq_analytics/generic_parquet_processor.rs
- rust/processor/src/bq_analytics/mod.rs
- rust/processor/src/db/common/models/default_models/parquet_transactions.rs
- rust/processor/src/gap_detectors/gap_detector.rs
- rust/processor/src/gap_detectors/mod.rs
- rust/processor/src/gap_detectors/parquet_gap_detector.rs
- rust/processor/src/processors/parquet_processors/parquet_default_processor.rs
- rust/processor/src/processors/parquet_processors/parquet_fungible_asset_processor.rs
- rust/processor/src/utils/counters.rs
- rust/processor/src/worker.rs
- rust/server-framework/src/lib.rs
There was a gap issue within the analytics pipeline. The new deployment restarted parquet processors, and it started from version stored in the `processor_status` alloydb table. however it wasn't working correctly b/c the table gets updated whenever the new parquet file gets uploaded to GCS, and the problem is that each table has a different frequency of uploads.  For example, for `move_resources`, because its size is bigger than any other structs, it gets uplaoded very frequency whereas move_modules reaches its max buffer size once every 30mins. and each file includes different rage of txn versions so that `processor status` is flaky. the version can go back and forth.  
Example failing scenario:
- last parquet file for `transactions` table hold a version 0-100000 -> file 1
- last …
> fix parquet to start from where it left off when it's re-deployed

- rust/processor/src/db/common/models/ans_models/mod.rs
- rust/processor/src/db/common/models/ans_models/parquet_ans_lookup_v2.rs
- rust/processor/src/processors/mod.rs
- rust/processor/src/processors/parquet_processors/mod.rs
- rust/processor/src/processors/parquet_processors/parquet_ans_processor.rs
- rust/processor/src/worker.rs
- Migrate ans_primary_name_v2 over to BQ, which includes v1
> Add parquet_ans_processor

- rust/processor/src/utils/counters.rs
- rust/processor/src/worker.rs
- Fix some latency counters for indexer processor
- Add batch size metrics
> Indexer processor metrics improvements. 

- rust/processor/src/bq_analytics/mod.rs
- rust/processor/src/db/common/models/events_models/mod.rs
- rust/processor/src/db/common/models/events_models/parquet_events.rs
- rust/processor/src/processors/mod.rs
- rust/processor/src/processors/parquet_processors/mod.rs
- rust/processor/src/processors/parquet_processors/parquet_ans_processor.rs
- rust/processor/src/processors/parquet_processors/parquet_default_processor.rs
- rust/processor/src/processors/parquet_processors/parquet_events_processor.rs
- rust/processor/src/processors/parquet_processors/parquet_fungible_asset_processor.rs
- rust/processor/src/processors/parquet_processors/parquet_transaction_metadata_processor.rs
- rust/processor/src/worker.rs
- added parquet events processors that migrates events table which also includes events_size_info (originally written by transaction_metadata_processor)
> Add Parquet Events Processor

- rust/processor/src/db/common/models/token_v2_models/parquet_v2_token_ownerships.rs
- rust/processor/src/processors/parquet_processors/parquet_token_v2_processor.rs
parquet token_v2_ownerships table was missing data. turns out it wasn't indexing some of changes like transfer and delete.
Note that we have some stale data in our DB where we have rows for self transfer, but we shouldn't index self transfer with events index. 
tested it not indexes the data that we were missing previously.
> add missing indexing delete reousrces

- rust/processor/src/processors/fungible_asset_processor.rs
there is missing logic for filtering coin_supply out from db writes.
tested locally that it's being filtered.
> add a logic to clear coin supply in fa processor as it's deprecated

- rust/processor/src/db/postgres/migrations/2024-08-16-213505_fix_collections_view/down.sql
- rust/processor/src/db/postgres/migrations/2024-08-16-213505_fix_collections_view/up.sql
Fix collections view to use current tables in the join 
Query is fixed in Petra.
> Fix current_collection_ownership_v2_view

- rust/Cargo.lock
- rust/processor/Cargo.toml
- rust/processor/src/db/common/models/fungible_asset_models/v2_fungible_asset_activities.rs
- rust/processor/src/db/common/models/fungible_asset_models/v2_fungible_asset_balances.rs
- rust/processor/src/processors/fungible_asset_processor.rs
Most part of this PR is just from auto-formatter.
This PR is trying to use rayon to process transactions in multiple threads. I moved all the hashmaps inside the loop (so assumption here is everything txn can be processed independently), and produces per txn output. The output is merged together at the very end.
The performance improvement depends on the machine spec. On my dev machine processing p2p transfer data is 10x+ faster.
> [Processor] Use multiple threads to speed up FA processor.

- .github/workflows/nightly-integration-tests.yaml
use runs-on instead of dockerhub to avoid rate limit issue. 
https://github.com/aptos-labs/aptos-indexer-processors/pull/490
> use runs on for nightly test

- rust/processor/src/gap_detectors/mod.rs
- rust/processor/src/gap_detectors/parquet_gap_detector.rs
QC failed due to a missing version at the boundary between parquet files around 9 AM on 8/22. Initially, metrics pointed to a possible grpc connection issue, but it was later discovered that there was a deployment occurred around that time.
tldr;
```
x - 1 = last success version
x = missing version
x + 1 = version it started post deployment
```
After reviewing the logs, I noticed that the parquet processor correctly updated the latest successful version to x just before the deployment. However, post deployment, it started processing from version x + 1. 
The root cause of this issue is a discrepancy between the gap detector and the parquet gap detector. While the worker correctly retrieves the start version by querying last_success_version and adding 1, the parquet gap detector keeps track …
> Fix offset issue within parquet gap detector to start with a correct version. 

- rust/processor/src/db/postgres/migrations/2024-08-20-224736_fa_migration_fix_part1/down.sql
- rust/processor/src/db/postgres/migrations/2024-08-20-224736_fa_migration_fix_part1/up.sql
- rust/processor/src/db/postgres/schema.rs
- rust/processor/src/processors/fungible_asset_processor.rs
- rust/processor/src/processors/mod.rs
- rust/processor/src/utils/database.rs
- rust/processor/src/worker.rs
- rust/sdk-processor/src/config/processor_config.rs
- rust/sdk-processor/src/utils/database.rs
Migration steps 
1. Swap Hasura to use `current_unified_fungible_asset_balances`
**[We're here]** 2. Add a killswitch on `current_unified_fungible_asset_balances_to_be_renamed` 
1. In addition, make a migration dropping columns. We want to split dropping columns separately from adding columns back so that we can add the columns without going through diesel migration again. 
2. Deploy the change with KS turned on. This should create no downtime since column dropping is quick.
3. Add generated columns back in dbeaver
4. Create new migration with added columns. Then remove KS. 
1. Also need to spin up backfill processor with KS turned off. 
5. Swap Hasura to use `current_unified_fungible_asset_balances_to_be_renamed`
Devnet: 570187040
Testnet: 5776192143
Mainnet: 1660732247
Confirmed that …
> [1/2][FA migration] Drop generated fields and add KS for unified

- rust/processor/src/db/common/models/fungible_asset_models/v2_fungible_asset_balances.rs
- rust/processor/src/db/postgres/migrations/2024-08-28-015552_fa_migration_fix_2/down.sql
- rust/processor/src/db/postgres/migrations/2024-08-28-015552_fa_migration_fix_2/up.sql
- rust/processor/src/db/postgres/schema.rs
- rust/processor/src/processors/fungible_asset_processor.rs
1. Swap Hasura to use `current_unified_fungible_asset_balances`
2. Add a killswitch on `current_unified_fungible_asset_balances_to_be_renamed` 
1. In addition, make a migration dropping columns. We want to split dropping columns separately from adding columns back so that we can add the columns without going through diesel migration again. 
2. Deploy the change with KS turned on. This should create no downtime since column dropping is quick.
**[This PR]**
3. Add generated columns back in dbeaver
4. Create new migration with added columns. Then remove KS. 
5. Rename `current_fungible_asset_balances` to `current_fungible_asset_balances_legacy` 
6. Rename `current_unified_fungible_asset_balances_to_be_renamed` to `current_fungible_asset_balances`
> [2/2][FA migration] Complete fa migration and rename table

- rust/processor/src/db/postgres/migrations/2024-09-03-232100_alter_signature_public_key_to_text/down.sql
- rust/processor/src/db/postgres/migrations/2024-09-03-232100_alter_signature_public_key_to_text/up.sql
- rust/processor/src/db/postgres/schema.rs
- rust/processor/src/processors/mod.rs
* Fix the long publicKey issue for the indexer processor: change type to `text`
* Example Transaction: https://devnet.aptoslabs.com/v1/transactions/by_version/53778191
* Tested locally and it looks good
> [indexer] alter public key to use text type.

- rust/processor/src/db/postgres/migrations/2024-09-10-215454_ans_registered_addr/down.sql
- rust/processor/src/db/postgres/migrations/2024-09-10-215454_ans_registered_addr/up.sql
There's a bug in the ANS contract where the primary name and the ANS don't point to the same registered address if a primary name token gets transfered. This caused the `current_aptos_names` view to show the wrong primary name because it joins only on `token_name`. We need to add a constraint to the left join on `current_ans_lookup_v2.registered_address = current_ans_primary_name_v2.registered_address`
Run the SQL and see that is_primary = false
> Fix current_aptos_names view

- rust/processor/src/db/common/models/coin_models/coin_activities.rs
- rust/processor/src/db/common/models/coin_models/coin_balances.rs
- rust/processor/src/db/common/models/coin_models/coin_infos.rs
- rust/processor/src/db/common/models/coin_models/coin_utils.rs
- rust/processor/src/db/common/models/default_models/write_set_changes.rs
- rust/processor/src/db/common/models/fungible_asset_models/parquet_v2_fungible_asset_balances.rs
- rust/processor/src/db/common/models/fungible_asset_models/v2_fungible_asset_balances.rs
- rust/processor/src/db/common/models/fungible_asset_models/v2_fungible_metadata.rs
- rust/processor/src/processors/ans_processor.rs
- rust/processor/src/processors/fungible_asset_processor.rs
[Context for onboarding task](https://www.notion.so/aptoslabs/Sean-Onboarding-46a443876035440f8c577a31ef015974?pvs=4#fc60141e2c714ba7bc1d6ccb921f4621)
Additional metadata (`write_set_change_index` and/or `txn_version`) to logs for easier debugging. 
Namely, logs in 
* `coin_utils.rs`
*  `write_set_changes.rs`
*  `ans_processor.rs`
The rest of the diff is just making the appropriate variables available for the logging. 
Ran `default_processor` (for wsc.unspecified logging),  `ans_processor` and `fungible_asset_processor` locally.
> Improve logging for indexer models and processors

- rust/processor/src/gap_detectors/mod.rs
Tested with parquet_ans_processor
when there is no transaction processed, log and do not update. 
when there is transaction processed, update the processor status
> skip updating processor status with null values for timestamp

- rust/processor/src/db/common/models/default_models/transactions.rs
- rust/processor/src/processors/default_processor.rs
> Remove unnecessary clones and use multi threads in default processor.

- rust/Cargo.lock
- rust/Cargo.toml
- rust/sdk-processor/src/steps/common/latest_processed_version_tracker.rs
- rust/sdk-processor/src/steps/events_processor/events_storer.rs
* Update the dependency version and rust version to be compatible with aptos-core.
> Update the rust version and depdnecy

- rust/indexer-metrics/src/main.rs
^
Root cause: some parquet tables don't have this value updated. 
Added both unit tests to cover the null and non-null cases.
> Fix the indexer metrics with nullable timestamp.

- rust/processor/src/processors/fungible_asset_processor.rs
The previous migration logic introduced db conflicts where v2 inserts were identified as v1 because we're filling asset_type_v1. This fixes that.
> [patch] Fix bug where we're identifying v2 inserts wrong

- rust/indexer-metrics/src/main.rs
- rust/integration-tests/src/event_processor/event_processor_tests.rs
- rust/processor/src/db/common/models/default_models/transactions.rs
- rust/processor/src/db/common/models/default_models/write_set_changes.rs
- rust/processor/src/gap_detectors/gap_detector.rs
- rust/processor/src/processors/default_processor.rs
We stopped writing some tables in default processor, this is to clean up the parsing logic and remove dead code. 
Ran a processor locally against testnet and verified that the numbers of rows written for the remaining tables are same as ones from testnet. checked using the SDM.
> clean up default processor

- .github/workflows/integration-tests.yaml
In order to trigger integ test from aptos-core repo, we need to have `repository_dispatch`
> allow cross repo workflow trigger

- .github/workflows/integration-tests.yaml
this is to allow aptos-core repo to trigger processor intregration test to support a case where json files are updated in aptos-core, we pass in commit hash along with the event, and it updates dependency using toml-cli. 
PR level test pass: https://github.com/aptos-labs/aptos-indexer-processors/actions/runs/11131978344
dispatch passed: https://github.com/aptos-labs/aptos-indexer-processors/actions/runs/11131969466
> allow cross repo workflow trigger (#526)

- .github/workflows/integration-tests.yaml
https://github.com/aptos-labs/aptos-indexer-processors/actions/runs/11153152318/job/31000121810
cargo lock doesn't get updated, so that triggered workflow fails at lint.
> update cargo.lock to fix lint failure

- .github/workflows/integration-tests.yaml
Currently, when aptos-core repo triggers processor integration tests,  there is no simple way for source repo to wait without having to poll the workflow jobs. However, the git api doesn't return payload or run_id that could be used to identify the actual triggered job. 
This is a workaround by adding a commit_hash to the run so that we can identify the job properly from aptos-core workflow. 
https://github.com/aptos-labs/aptos-indexer-processors/actions/runs/11153523032/job/31001187434
> add uui to workflow job name

- .github/workflows/build-images.yaml
- .github/workflows/copy-processor-images-to-dockerhub-release.yaml
- scripts/build-and-push-images.sh
Builds off of special branches like `main` get image tags now in the form:
* `<branch_name>`
* `<branch_name>_<git_sha>`
This is useful for Forge, which by default should use the latest stable processors version. Currently it's pinned to some recent commit hash
Also general cleanup of branch push triggers
Canary runs on push to PR branch. It pushes all the expected tags
```
INFO[0237] Pushing image to us-docker.pkg.dev/aptos-registry/docker/indexer-client-examples/rust:dbd773c4d0c6c4bac21bc210dadd87eb0b11863c 
INFO[0240] Pushed us-docker.pkg.dev/aptos-registry/docker/indexer-client-examples/rust@sha256:6776a413b25dd4ec6a632a34719376ff36366e192f2999c4704d2b3200431481 
INFO[0240] Pushing image to us-docker.pkg.dev/aptos-registry/docker/indexer-client-examples/rust:rustielin-branch-prefix-bui …
```
> [gha/docker] build with branch name; also cleanup

- .github/workflows/lint.yaml
We already have a separate github action that runs cargo test.
> remove cargo test from lint workflow

- rust/processor/src/db/common/models/user_transactions_models/mod.rs
- rust/processor/src/db/common/models/user_transactions_models/parquet_signatures.rs
- rust/processor/src/db/common/models/user_transactions_models/parquet_user_transactions.rs
- rust/processor/src/processors/mod.rs
- rust/processor/src/processors/parquet_processors/mod.rs
- rust/processor/src/processors/parquet_processors/parquet_user_transactions_processor.rs
- rust/processor/src/worker.rs
Modified schema based on feedback from https://github.com/aptos-labs/aptos-indexer-processors/pull/513
New schema: 
```
pub txn_version: i64,
pub block_height: i64,
pub parent_signature_type: String,
pub sender: String,
pub sequence_number: i64,
pub max_gas_amount: u64,
pub expiration_timestamp_secs: u64,
pub gas_unit_price: u64,
pub gas_used: u64,
#[allocative(skip)]
pub timestamp: chrono::NaiveDateTime,
pub entry_function_id_str: String,
pub epoch: i64,
pub gas_fee_payer_address: Option<String>,
pub is_transaction_success: bool,
pub storage_refund_amount: u64,
pub num_signatures: i64,
```
> [parquet] add user transactions table to parquet

- rust/Cargo.lock
- rust/Cargo.toml
- rust/processor/src/processors/fungible_asset_processor.rs
- rust/processor/src/worker.rs
- rust/sdk-processor/src/config/indexer_processor_config.rs
- rust/sdk-processor/src/config/processor_config.rs
- rust/sdk-processor/src/processors/events_processor.rs
- rust/sdk-processor/src/processors/fungible_asset_processor.rs
- rust/sdk-processor/src/processors/mod.rs
- rust/sdk-processor/src/steps/common/latest_processed_version_tracker.rs
- rust/sdk-processor/src/steps/events_processor/events_extractor.rs
- rust/sdk-processor/src/steps/events_processor/events_storer.rs
- rust/sdk-processor/src/steps/fungible_asset_processor/fungible_asset_extractor.rs
- rust/sdk-processor/src/steps/fungible_asset_processor/fungible_asset_storer.rs
- rust/sdk-processor/src/steps/fungible_asset_processor/mod.rs
- rust/sdk-processor/src/steps/mod.rs
- Upgrade SDK dependency to latest version
- Migrate FungibleAssetProcessor to
- Add FungibleAssetExtractor and FungibleAssetStorer steps
- Update config to support FungibleAssetProcessor
- Add support for deprecated tables flags
Run fa processor
> Migrate FA processor to SDK

- rust/sdk-processor/src/processors/events_processor.rs
- rust/sdk-processor/src/processors/fungible_asset_processor.rs
- rust/sdk-processor/src/steps/common/latest_processed_version_tracker.rs
This PR adds OrderByVersionStep to events and FA processors. It also updates LatestVersionTrackerStep to assume the transactions batches are coming in order.
Next PR: Parallelize storer 
Run FA processor
> Add `order` step to SDK processors

- rust/processor/src/db/postgres/migrations/2024-10-23-232703_num_active_delegator_per_pool/down.sql
- rust/processor/src/db/postgres/migrations/2024-10-23-232703_num_active_delegator_per_pool/up.sql
When a delegator first receives a delegation in the UI it will show as having 3 active delegators.
ex. https://explorer.aptoslabs.com/txn/1828020008/changes?network=mainnet
The 3 table items with balance are
1. reward address
2. NULL address
3. delegator
I've changed the tooltip to reflect that reward address will be included https://github.com/aptos-labs/explorer/pull/836
This logic change removes the NULL address from being counted
Context on NULL address https://github.com/aptos-labs/aptos-core/blob/114d361d6cc7119f88eec11ae562c5ec6797275a/aptos-move/framework/aptos-framework/sources/delegation_pool.move#L1568
> remove null address from delegator count

- rust/sdk-processor/src/steps/common/processor_status_saver.rs
- rust/sdk-processor/src/utils/starting_version.rs
If the backfillStatus is Complete on a particular row, while the processor will correctly start to backfill from 0 again, the table will not reflect the current status due to the monotonic increasing invariant set on the table writes. A workaround was to simply remove that invariant. 
This PR adds back that invariant to avoid possible edge cases and instead resets the latestSuccessVersion to 0 in the `starting_version` logic upon encountering the `Complete` state.
Manually tested expected behavior:
> Reset LastSuccessfulVersion to 0 if Restarting on Stauts=Complete

- .github/actions/rust-setup/action.yaml
- .github/workflows/integration-tests.yaml
- rust/Cargo.lock
- rust/Cargo.toml
use generate-output flag to generate when when new txn inputs are deteced so that integration test triggering workflow in aptos-core doesn't fail. 
added a follow-up task in the. test coverage milestones: https://www.notion.so/aptoslabs/Indexer-Test-Coverage-11a8b846eb7280868323d79a37313478?pvs=4#12e8b846eb728018b3faccd83e09d80f
triggered the test against the branch and passed. 
https://github.com/aptos-labs/aptos-indexer-processors/actions/runs/11583791402
> update integration test workflow

- rust/processor/src/processors/stake_processor.rs
- rust/sdk-processor/src/config/indexer_processor_config.rs
- rust/sdk-processor/src/config/processor_config.rs
- rust/sdk-processor/src/processors/mod.rs
- rust/sdk-processor/src/processors/stake_processor.rs
- rust/sdk-processor/src/steps/mod.rs
- rust/sdk-processor/src/steps/stake_processor/mod.rs
- rust/sdk-processor/src/steps/stake_processor/stake_extractor.rs
- rust/sdk-processor/src/steps/stake_processor/stake_storer.rs
- Refactor existing stake processor to locate all parsing logic in `parse_stake_data`.
- Rewrite stake processor using the sdk
- add new, non-default ProcessorConfig called StakeProcessorConfig that contains additional fields to the default one. Namely, query_retries, query_retry_delay_ms.
> Rewrite Stake Processor with SDK

- rust/processor/src/processors/objects_processor.rs
- rust/sdk-processor/src/config/indexer_processor_config.rs
- rust/sdk-processor/src/config/processor_config.rs
- rust/sdk-processor/src/processors/mod.rs
- rust/sdk-processor/src/processors/objects_processor.rs
- rust/sdk-processor/src/steps/events_processor/events_extractor.rs
- rust/sdk-processor/src/steps/mod.rs
- rust/sdk-processor/src/steps/objects_processor/mod.rs
- rust/sdk-processor/src/steps/objects_processor/objects_extractor.rs
- rust/sdk-processor/src/steps/objects_processor/objects_storer.rs
Migrate objects processor to SDK
> Migrate objects processor to SDK

- rust/sdk-processor/src/config/processor_config.rs
- rust/sdk-processor/src/parquet_processors/parquet_default_processor.rs
- rust/sdk-processor/src/utils/starting_version.rs
https://www.notion.so/aptoslabs/Update-run_processor-Function-12d8b846eb7280268d65c0d92d2e328a?pvs=4
> [parquet-sdk-migration] add a logic to determine the starting version for parquet processor

- rust/integration-tests/src/sdk_tests/objects_processor_tests.rs
- rust/integration-tests/src/sdk_tests/stake_processor_tests.rs
- rust/integration-tests/src/sdk_tests/token_v2_processor_tests.rs
Single transaction test should not need to lookup any data in the DB since it won't exist anyway. Lower the lookup retries and wait time to speed up the test. 
Before
```
test sdk_tests::stake_processor_tests::tests::mainnet_stake_gov_record_txn has been running for over 60 seconds
test sdk_tests::stake_processor_tests::tests::mainnet_stake_pool_delegation_txn has been running for over 60 seconds
```
After
`cargo test` runs fine
> Speed up tests by avoiding long lookups 

- rust/processor/src/processors/user_transaction_processor.rs
- rust/sdk-processor/src/config/indexer_processor_config.rs
- rust/sdk-processor/src/config/processor_config.rs
- rust/sdk-processor/src/processors/mod.rs
- rust/sdk-processor/src/processors/monitoring_processor.rs
- rust/sdk-processor/src/processors/user_transaction_processor.rs
- rust/sdk-processor/src/steps/mod.rs
- rust/sdk-processor/src/steps/user_transaction_processor/mod.rs
- rust/sdk-processor/src/steps/user_transaction_processor/user_transaction_extractor.rs
- rust/sdk-processor/src/steps/user_transaction_processor/user_transaction_storer.rs
Add User Transaction Processor
Add Monitoring Processor
Its just the transaction stream since the processor just no-ops
> Add Monitoring and User Transaction Processors

- .github/workflows/integration-tests.yaml
The `generate-output` flag is no longer needed as `all_tests` has been deprecated in #598
> Remove Generate Output Option in Integration Test GHA

- rust/Cargo.lock
- rust/Cargo.toml
- rust/integration-tests/src/models/account_transaction_models.rs
- rust/processor/Cargo.toml
- rust/processor/src/db/common/models/account_transaction_models/account_transactions.rs
- rust/processor/src/db/common/models/coin_models/coin_utils.rs
- rust/processor/src/db/common/models/fungible_asset_models/parquet_v2_fungible_asset_balances.rs
- rust/processor/src/db/common/models/fungible_asset_models/v2_fungible_asset_balances.rs
- rust/processor/src/db/common/models/fungible_asset_models/v2_fungible_asset_utils.rs
- rust/processor/src/db/common/models/fungible_asset_models/v2_fungible_metadata.rs
- rust/processor/src/db/common/models/mod.rs
- rust/processor/src/db/common/models/object_models/v2_object_utils.rs
- rust/processor/src/db/common/models/resources.rs
- rust/processor/src/db/common/models/token_models/token_utils.rs
- rust/processor/src/db/common/models/token_v2_models/parquet_v2_token_datas.rs
- rust/processor/src/db/common/models/token_v2_models/parquet_v2_token_ownerships.rs
- rust/processor/src/db/common/models/token_v2_models/v2_collections.rs
- rust/processor/src/db/common/models/token_v2_models/v2_token_datas.rs
- rust/processor/src/db/common/models/token_v2_models/v2_token_metadata.rs
- rust/processor/src/db/common/models/token_v2_models/v2_token_ownerships.rs
- rust/processor/src/db/common/models/token_v2_models/v2_token_utils.rs
- rust/processor/src/processors/fungible_asset_processor.rs
- rust/processor/src/processors/nft_metadata_processor.rs
- rust/processor/src/processors/objects_processor.rs
- rust/processor/src/processors/parquet_processors/parquet_fungible_asset_activities_processor.rs
- rust/processor/src/processors/parquet_processors/parquet_fungible_asset_processor.rs
- rust/processor/src/processors/parquet_processors/parquet_token_v2_processor.rs
- rust/processor/src/processors/token_v2_processor.rs
- rust/sdk-processor/src/steps/objects_processor/objects_extractor.rs
This PR is trying to move some common logic/type/constant to resources.rs, avoid duplicate/unnecessary parsing/deserialization logic when converting between generic write resource and a specific resource type.
The main motivation is to improve the performance, no other behavior change is expected.
To give an idea on the performance impact, when running simple token minting workload, the processing time of token_v2_processor is 5x less than before.
This PR only handles FA and TokenV2 resources, leave other resources like Coin and Token for future PRs.
> [Processor] Simplify some logic to reduce unnecessary duplicated work.

- .github/workflows/test-coverage.yaml
- README.md
Introducing a CI workflow to track and report test coverage using cargo llvm-cov and integrates with Codecov for visualization. The workflow runs daily or on PRs, generates an lcov report, and uploads it to Codecov. It also updates the README.md to include a Codecov badge for coverage metrics. This aims to improve code quality by providing continuous visibility into test coverage and highlighting untested areas.
https://app.codecov.io/github/aptos-labs/aptos-indexer-processors/tree/11-06-_indexer-test-coverage_add_test_coverage_ci
we can find our coverage here.
- will need to investigate if we can specify the directory we would like to track as a indexer coverage
> [indexer-test-coverage] add test coverage ci

- rust/sdk-processor/src/steps/parquet_default_processor/parquet_default_extractor.rs
- rust/sdk-processor/src/utils/parquet_extractor_helper.rs
this will reduce some potential duplicate codes from parquet migration
> refactor parquet extractor backfill support function

- rust/processor/src/db/postgres/migrations/2024-12-02-190328_ans_view_is_active_fix/down.sql
- rust/processor/src/db/postgres/migrations/2024-12-02-190328_ans_view_is_active_fix/up.sql
Fix `current_aptos_names.is_active` to check the domain expiration policy if the subdomain expiration policy is set to 1. 
0 is manual
1 follows the domain expiration
justin.petra.apt is active and primary
poggers.apt is not active and not primary
> Fix current_aptos_names to check domain expiration policy

- rust/processor/src/processors/fungible_asset_processor.rs
- rust/processor/src/processors/objects_processor.rs
1. Add Untransferable resource parsing to objects processor. It uses the `objects_metadata_helper.untransferable` but not actually parsing/inserting it into `objects_metadata_helper` so this fixes that.
2. Delete Untransferable parsing from fa processor since it doesn't use the field. fa processor indexes `is_frozen` which is not about objects transferability, but whether the store itself is frozen. 
Run objects and fa processor. Integration tests will be added later since merging to aptos-core is currently broken.
> Fix untransferable parsing

- rust/Cargo.lock
- rust/Cargo.toml
- rust/integration-tests/sdk_expected_db_output_files/objects_processor/test_untransferable/current_objects.json
- rust/integration-tests/sdk_expected_db_output_files/objects_processor/test_untransferable/objects.json
- rust/integration-tests/src/sdk_tests/objects_processor_tests.rs
cargo run objects_processor_tests
> untransferable tests

- rust/sdk-processor/src/utils/starting_version.rs
This will now use `starting_version` when there's no checkpoint in `processor_status`.
> Return None when no entry found in processor_status

- rust/processor/src/db/common/models/account_transaction_models/mod.rs
- rust/processor/src/db/common/models/account_transaction_models/raw_account_transactions.rs
- rust/processor/src/db/common/models/mod.rs
- rust/processor/src/db/parquet/models/account_transaction_models/mod.rs
- rust/processor/src/db/parquet/models/account_transaction_models/parquet_account_transactions.rs
- rust/processor/src/db/parquet/models/mod.rs
- rust/processor/src/db/postgres/models/account_transaction_models/account_transactions.rs
- rust/processor/src/processors/account_transactions_processor.rs
- rust/sdk-processor/src/config/indexer_processor_config.rs
- rust/sdk-processor/src/config/processor_config.rs
- rust/sdk-processor/src/parquet_processors/mod.rs
- rust/sdk-processor/src/parquet_processors/parquet_account_transactions_processor.rs
- rust/sdk-processor/src/steps/account_transactions_processor/account_transactions_extractor.rs
- rust/sdk-processor/src/steps/mod.rs
- rust/sdk-processor/src/steps/parquet_account_transactions_processor/mod.rs
- rust/sdk-processor/src/steps/parquet_account_transactions_processor/parquet_account_transactions_extractor.rs
migrating parquet account txn processor to sdk
mroe rows in parquet is expected
> Migrate parquet account txn processor to sdk

- rust/processor/src/db/common/models/mod.rs
- rust/processor/src/db/common/models/token_v2_models/mod.rs
- rust/processor/src/db/common/models/token_v2_models/raw_token_claims.rs
- rust/processor/src/db/parquet/models/mod.rs
- rust/processor/src/db/parquet/models/token_v2_models/mod.rs
- rust/processor/src/db/parquet/models/token_v2_models/token_claims.rs
- rust/processor/src/db/postgres/models/token_v2_models/v2_token_activities.rs
- rust/processor/src/processors/token_v2_processor.rs
- rust/sdk-processor/src/config/indexer_processor_config.rs
- rust/sdk-processor/src/config/processor_config.rs
- rust/sdk-processor/src/parquet_processors/mod.rs
- rust/sdk-processor/src/parquet_processors/parquet_token_v2_processor.rs
- rust/sdk-processor/src/steps/mod.rs
- rust/sdk-processor/src/steps/parquet_token_v2_processor/mod.rs
- rust/sdk-processor/src/steps/parquet_token_v2_processor/parquet_token_v2_extractor.rs
- rust/sdk-processor/src/steps/token_v2_processor/token_v2_extractor.rs
- migrated pending claims
ran both legacy and sdk postgres processor .. num of rows match for all three.
> [parquet-sdk][token_v2] migrate token_v2_pending_claims

- rust/processor/src/db/common/models/token_v2_models/mod.rs
- rust/processor/src/db/common/models/token_v2_models/raw_v1_token_royalty.rs
- rust/processor/src/db/parquet/models/token_v2_models/mod.rs
- rust/processor/src/db/parquet/models/token_v2_models/v1_token_royalty.rs
- rust/processor/src/processors/token_v2_processor.rs
- rust/processor/src/utils/table_flags.rs
- rust/sdk-processor/src/config/processor_config.rs
- rust/sdk-processor/src/parquet_processors/mod.rs
- rust/sdk-processor/src/parquet_processors/parquet_token_v2_processor.rs
- rust/sdk-processor/src/steps/parquet_token_v2_processor/parquet_token_v2_extractor.rs
- rust/sdk-processor/src/steps/token_v2_processor/token_v2_extractor.rs
- added RawCurrentTokenRoyalty models
-
ran both legacy and sdk postgres processor .. num of rows match for all three.
> [parquet-sdk][token_v2] migrate CurrentTokenRoyaltyV1

- rust/processor/src/db/common/models/token_v2_models/mod.rs
- rust/processor/src/db/common/models/token_v2_models/raw_v2_token_metadata.rs
- rust/processor/src/db/parquet/models/token_v2_models/mod.rs
- rust/processor/src/db/parquet/models/token_v2_models/v2_token_metadata.rs
- rust/processor/src/processors/token_v2_processor.rs
- rust/sdk-processor/src/config/processor_config.rs
- rust/sdk-processor/src/parquet_processors/mod.rs
- rust/sdk-processor/src/parquet_processors/parquet_token_v2_processor.rs
- rust/sdk-processor/src/steps/parquet_token_v2_processor/parquet_token_v2_extractor.rs
- rust/sdk-processor/src/steps/token_v2_processor/token_v2_extractor.rs
- add Raw CurrentTokenV2Metadata
- migrated CurrentTokenV2Metadata
ran both legacy and sdk postgres processor .. num of rows match for all three.
> [parquet-sdk][token_v2] migrate CurrentTokenV2Metadata

- rust/processor/src/db/common/models/token_v2_models/mod.rs
- rust/processor/src/db/common/models/token_v2_models/raw_v2_token_datas.rs
- rust/processor/src/db/parquet/models/mod.rs
- rust/processor/src/db/parquet/models/token_v2_models/mod.rs
- rust/processor/src/db/parquet/models/token_v2_models/v2_token_datas.rs
- rust/processor/src/db/parquet/models/token_v2_models/v2_token_ownerships.rs
- rust/processor/src/db/postgres/models/token_v2_models/mod.rs
- rust/processor/src/db/postgres/models/token_v2_models/v2_token_datas.rs
- rust/processor/src/processors/nft_metadata_processor.rs
- rust/processor/src/processors/parquet_processors/parquet_token_v2_processor.rs
- rust/processor/src/processors/token_v2_processor.rs
- rust/sdk-processor/src/config/processor_config.rs
- rust/sdk-processor/src/parquet_processors/mod.rs
- rust/sdk-processor/src/parquet_processors/parquet_token_v2_processor.rs
- rust/sdk-processor/src/steps/parquet_token_v2_processor/parquet_token_v2_extractor.rs
- rust/sdk-processor/src/steps/token_v2_processor/token_v2_extractor.rs
- Compared the number of rows from DE teams BigQuery table, testing BigQuery table, legacy processor table, and sdk processor table
> [parquet-sdk][token_v2] migrate TokenDataV2 and CurrentTokenDataV2

- rust/sdk-processor/src/utils/starting_version.rs
parquet processor was always starting from the min processed version or 0 if not all tables are processed. And we would like the consistency across all processors where it should start from the higher version.
> enable parquet to start processing from the specified starting version in the config

- rust/processor/src/db/common/models/object_models/raw_v2_objects.rs
- rust/processor/src/db/common/models/token_v2_models/raw_v2_token_ownerships.rs
- rust/processor/src/db/parquet/models/mod.rs
- rust/processor/src/db/parquet/models/object_models/v2_objects.rs
- rust/processor/src/processors/objects_processor.rs
- rust/processor/src/processors/parquet_processors/parquet_token_v2_processor.rs
- rust/processor/src/processors/token_v2_processor.rs
- rust/processor/src/utils/database.rs
- rust/sdk-processor/src/config/indexer_processor_config.rs
- rust/sdk-processor/src/config/processor_config.rs
- rust/sdk-processor/src/parquet_processors/mod.rs
- rust/sdk-processor/src/parquet_processors/parquet_objects_processor.rs
- rust/sdk-processor/src/steps/common/gcs_uploader.rs
- rust/sdk-processor/src/steps/mod.rs
- rust/sdk-processor/src/steps/objects_processor/objects_extractor.rs
- rust/sdk-processor/src/steps/parquet_objects_processor/mod.rs
- rust/sdk-processor/src/steps/parquet_objects_processor/parquet_objects_extractor.rs
- rust/sdk-processor/src/steps/parquet_token_v2_processor/parquet_token_v2_extractor.rs
- rust/sdk-processor/src/steps/token_v2_processor/token_v2_extractor.rs
- migrate objects 
- for parquet, we want to avoid lookups for deleted resource. so we replaced with default values, which will be handled during the load as a part of qc pipeline.
```
Self {
transaction_version: txn_version,
write_set_change_index,
object_address: resource.address.clone(),
owner_address: DELETED_RESOURCE_OWNER_ADDRESS.to_string(),   <-------
state_key_hash: resource.state_key_hash.clone(),
guid_creation_num: BigDecimal::default(),       <-------
allow_ungated_transfer: false,     <-------
is_deleted: true,
untransferrable: false,          <-------
block_timestamp: chrono::NaiveDateTime::default(),      <-------
```
these fields are the ones from the prev owner
- Compared the number of rows from DE teams BigQuery table, testing BigQuery table, legacy processor table, and …
> [parquet-sdk]migrate objects [pt2]

- rust/integration-tests/sdk_expected_db_output_files/user_transaction_processor/test_multi_ed25519/user_transactions.json
- rust/integration-tests/sdk_expected_db_output_files/user_transaction_processor/test_multi_key_keyless_signature/user_transactions.json
- rust/integration-tests/sdk_expected_db_output_files/user_transaction_processor/test_single_ed25519/user_transactions.json
- rust/integration-tests/sdk_expected_db_output_files/user_transaction_processor/test_single_key_ed25519/user_transactions.json
- rust/integration-tests/sdk_expected_db_output_files/user_transaction_processor/test_single_key_secp/user_transactions.json
- rust/integration-tests/sdk_expected_db_output_files/user_transaction_processor/test_single_sender_ed25519/user_transactions.json
- rust/integration-tests/sdk_expected_db_output_files/user_transaction_processor/test_single_sender_keyless/user_transactions.json
- rust/integration-tests/sdk_expected_db_output_files/user_transaction_processor/test_single_sender_secp/user_transactions.json
- rust/integration-tests/sdk_expected_db_output_files/user_transaction_processor/test_single_sender_webauth/user_transactions.json
- rust/integration-tests/src/models/user_transactions_models.rs
- rust/processor/src/db/postgres/migrations/2025-01-07-000504_add_function_columns_to_user_transactions/down.sql
- rust/processor/src/db/postgres/migrations/2025-01-07-000504_add_function_columns_to_user_transactions/up.sql
- rust/processor/src/db/postgres/models/user_transactions_models/user_transactions.rs
- rust/processor/src/db/postgres/schema.rs
- rust/processor/src/utils/util.rs
Following https://aptos-org.slack.com/archives/C03MN5F7WUV/p1734539332759199 , adding `contract_address`, `module_name`, and `function_name` columns to the `user_transactions` table to index each of the entry function string data separately.
> Add columns to `user_transactions` table

- rust/integration-tests/src/models/user_transactions_models.rs
- rust/processor/src/db/postgres/migrations/2025-01-07-000504_add_function_columns_to_user_transactions/up.sql
- rust/processor/src/db/postgres/models/user_transactions_models/user_transactions.rs
- rust/processor/src/db/postgres/schema.rs
Fixes a db migration error where existing rows had null values for the new columns
> Remove null constraint on new user_transaction rows

- rust/processor/src/processors/user_transaction_processor.rs
Set `ON CONFLICT` fields for the `user_transaction` columns that need to be backfilled
Tested locally
> Backfill user_transaction fields

- rust/Cargo.lock
- rust/Cargo.toml
- rust/processor/Cargo.toml
- rust/processor/src/db/postgres/models/property_map.rs
Ensure that the property maps from tokens maintain their order, to prevent deltas between different versions due to different keys (but with same data)
> Retain order for property maps

- rust/Cargo.toml
- rust/server-framework/Cargo.toml
This dependency causes some build issues, because it's expected to exist at the workspace level.  So, even though it's not required for anything, it still has to be downloaded.
Now, this prevents this from occurring, making sure it's only loaded for linux.
This is what happened before:
```
Run scripts/cli/build_cli_release.sh "macOS" "6.0.1"
Building release 6.0.1 of aptos-cli for Darwin-macOS on arm64
Updating git repository `https://github.com/aptos-labs/futures-rs`
Updating git repository `https://github.com/aptos-labs/merlin`
Updating git repository `https://github.com/aptos-labs/serde-reflection`
Updating git repository `https://github.com/aptos-labs/x2551[9](https://github.com/gregnazario/aptos-core/actions/runs/12774871815/job/35609926121#step:4:10)-dalek`
Updating git repository …
```
> [deps] Move linux dependency to crate instead of workspace

- .github/workflows/update-sdk-dependency.yaml
> Fix proto-related release workflow. 

- rust/Cargo.lock
- rust/processor/src/db/postgres/models/fungible_asset_models/v2_fungible_asset_balances.rs
There's a bug [here](https://cloud.hasura.io/public/graphiql?endpoint=https%3A%2F%2Findexer.mainnet.aptoslabs.com%2Fv1%2Fgraphql&query=query+MyQuery+%40cached%28refresh%3A+true%29+%7B%0A++current_fungible_asset_balances%28%0A++++where%3A+%7Basset_type%3A+%7B_eq%3A+%220x180e877b151107d7d180545c2fdb373578740872a59071f636c62bd60a6b249d%22%7D%2C+owner_address%3A+%7B_eq%3A+%220xa720111403ccc18055b8ed89e57ed2f85294a4950cd2c42948b63403c1be9198%22%7D%7D%0A++++limit%3A+10%0A++%29+%7B%0A++++owner_address%0A++++amount%0A++++amount_v1%0A++++amount_v2%0A++++asset_type%0A++++asset_type_v1%0A++++asset_type_v2%0A++++last_transaction_version_v1%0A++++last_transaction_version_v2%0A++%7D%0A%7D%0A&__cf_chl_tk=dHmIYscLKW6.rw1CVtevzhOYtkE3vv3nVSQfFHhXyg8-1737483972-1.0.1.1-ji4NYpGheFnI2345vMZfMxgoW57v7pn6AZcAKu …
> [FA migration] Fix asset_type_v1 overridden by null
